### ISSUE TITLE
INTERNAL ERROR: invalid error code fffffffe (Ring Index out of range) in MPID_nem_tcp_init:373

### ISSUE THREAD

**Issue by junghans** [pmodels/mpich#4318] opened 2020-02-12 03:42 UTC
This was reported twice on Fedora, once in https://bugzilla.redhat.com/show_bug.cgi?id=1793563 for the espressomd package and once in https://bugzilla.redhat.com/show_bug.cgi?id=1799473 for Gromacs. This is using mpich-devel-3.3.2-3.fc32.aarch64 for Gromacs.

**Comment by junghans** [comment] 2020-02-12 03:46
To reproduce this on Fedora do:
```
fedpkg clone -a gromacs
cd gromacs
spectool -g gromacs.spec
fedpkg srpm
mock -r fedora-rawhide-aarch64 --no-clean gromacs-2019.5-2.fc32.1.src.rpm
```

**Comment by hzhou** [comment] 2020-02-12 05:03
The bug report comment with detailed error message: https://bugzilla.redhat.com/show_bug.cgi?id=1799473#c7

**Comment by hzhou** [comment] 2020-02-12 05:04
It is fixed in this commit: https://github.com/pmodels/mpich/pull/4181/commits/8d923937ec5d1362274817eee5228690da24e974

@raffenet Apparently we neglected to pick this commit on the ch3 branch last year.

**Comment by raffenet** [comment] 2020-02-22 22:22
@junghans patches applied to the 3.3.x branch should fix the issue. We do not currently have a plan to cut a 3.3.3 release. Will that be a problem?

**Comment by junghans** [comment] 2020-02-23 18:20
> @junghans patches applied to the 3.3.x branch should fix the issue. We do not currently have a plan to cut a 3.3.3 release. Will that be a problem?

No worries, we patched it in for now: https://src.fedoraproject.org/rpms/mpich/pull-request/2

**Comment by hzhou** [comment] 2020-11-03 18:19
Looks like this issue is fixed.

**Closed by hzhou** 2020-11-03 18:19 UTC

**Comment by aarograh** [comment] 2023-04-03 14:26
Hello, I've encountered a very similar issue using mpich 3.3.2:
```
Invalid error code (-1) (error ring index 127 invalid)
INTERNAL ERROR: invalid error code ffffffff (Ring Index out of range) in MPID_nem_delete_shm_region:957
```
There are very minor differences in the the error message (error code -1 for me instead of -2 in this issue; MPID_nem_delete_shm_region for me as opposed to MPID_nem_tcp_init for the issue).  Do you think the patch created for this issue would also resolve my error, or are they probably unrelated?  Unfortunately the code I'm using is export controlled so I cannot easily provide concrete examples to reproduce the error.

**Comment by aarograh** [comment] 2023-04-03 14:38
> @aarograh It is likely unrelated. The error message is a catch-all for all internal errors that we neglected to generate a proper error code. Could you try the latest MPICH release (4.1.1)? If the issue persists, please create an issue.

Thank you for the prompt response!  I will try a newer MPICH release like you suggested.
