### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Catherine9826** [pmodels/mpich#6445] opened 2023-03-16 11:42 UTC
When i run mpiexec, it said "Segmentation fault (core dumped)".
When i run mpiexec -n 32 maker, it said :
```
STATUS: Parsing control files...
STATUS: Processing and indexing input FASTA files...

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 2677504 RUNNING AT zzs
=   EXIT CODE: 9
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
```

**Comment by Catherine9826** [comment] 2023-03-17 03:17
> Can you capture a backtrace from the coredump? That would help pin down if the segfault comes from MPICH code or application code.

I got this：
[930810.666860] mpiexec[3026634]: segfault at 562ba64e3000 ip 0000562ba617433a sp 00007ffc25d38cf0 error 6 in mpiexec.hydra[562ba6155000+3d000]
[930810.666874] Code: 75 a8 41 89 cd 0f 1f 00 41 8d 45 01 4d 63 ed 48 85 ed 0f 84 27 01 00 00 48 89 ee 8b 4e 08 4a 8d 3c aa 85 c9 7e 40 44 8b 46 10 <44> 89 07 39 c3 0f 84 fb 00 00 00 83 e9 01 48 98 4a 8d 7c 29 01 eb

**Comment by raffenet** [comment] 2023-03-17 14:08
Can you recompile MPICH with `--enable-g` so more information is available in the backtrace? Can you also share what version of MPICH you are using?

**Comment by HathewayWill** [comment] 2023-04-22 09:24
Similar problem. 

32 cores crashes mpich. 16 runs just fine

**Comment by hzhou** [comment] 2023-06-13 20:49
@Catherine9826 @HathewayWill Could you find a reproducer or a backtrace?

**Comment by HathewayWill** [comment] 2023-06-13 20:54
> @Catherine9826 @HathewayWill Could you find a reproducer or a backtrace? 

I couldn't

**Comment by hzhou** [comment] 2023-06-23 13:16
I am closing this issue due to lack of details. Please reopen with more details.

**Closed by hzhou** 2023-06-23 13:16 UTC

**Comment by Minyoung-sss** [comment] 2024-04-01 08:58
Hello 

I have a simliar problem.

When I ran MPICH (version 4.1.2),  it said "Segmentation fault"


```
STATUS: Parsing control files...
STATUS: Processing and indexing input FASTA files...

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 1310718 RUNNING AT kucmb-System-Product-Name
=   EXIT CODE: 9
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
```
so, I you recompile MPICH with --enable-g when you talked.
But I didn't get a backtrace when I ran this command
`mpiexec -np 10 gdb --args maker`

I think this reason is 'maker' which is perl script using /usr/bin/perl

So I ran again `mpiexec -np 10 gdb --args /usr/bin/perl` 

```
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/perl...
(No debugging symbols found in /usr/bin/perl)
(gdb) Reading symbols from /usr/bin/perl...
(No debugging symbols found in /usr/bin/perl)
(gdb) Reading symbols from /usr/bin/perl...
(No debugging symbols found in /usr/bin/perl)
(gdb) Reading symbols from /usr/bin/perl...
(No debugging symbols found in /usr/bin/perl)
(gdb) Reading symbols from /usr/bin/perl...
(No debugging symbols found in /usr/bin/perl)
```
This command came out.

I want to solve this problem and get other detail to you to make progress.

How to give you detail?

Thank you

**Comment by hzhou** [comment] 2024-04-01 14:26
@Minyoung-sss Is the code open source to look at? Any error may cause segfaults, which often have nothing to do with MPICH. Looks like the `maker` perl code is causing Perl to segfault here? Try narrow it down. We can't help until we have a reproducer that we can probe.

**Comment by Minyoung-sss** [comment] 2024-04-02 11:12
Hello Thank you for your reply.

I got maker perl code here 
`wget http://weatherby.genetics.utah.edu/maker_downloads/AD6E/A1B0/C2B7/558563CFD35E343BA1B888148294/maker-3.01.04.tgz`

I think maker perl code isn't casuing Perl to segfault.....
I don't know what is problem and how to try narrow it down...

**Comment by hzhou** [comment] 2024-04-02 16:08
We need locate the source of segfaults. Here is a guide on how to do that: https://jvns.ca/blog/2018/04/28/debugging-a-segfault-on-linux/. If the segfaults is inside MPICH and since you build it with debug symbols, gdb should be able to locate that. I suspect the segfault is outside MPICH.

**Comment by hzhou** [comment] 2024-07-17 16:42
@lrtfm Thanks for providing trace log. Looks like your processes failed creating shared memory. The segfault was triggered when it tries to write to the shared memory.  I am not sure what is the reason shared memory fails. In the meantime, you may want to try 1. build mpich with `--with-device=ch4` or 2. run with `MPIR_CVAR_NO_LOCAL=1`

**Comment by lrtfm** [comment] 2024-07-17 17:06
@hzhou Thank you for your suggestions. I tried both options. Both options worked well.

Does this confirm that the issue is related to shared memory? Could you guide me on how to confirm or debug shared memory issues?

**Comment by hzhou** [comment] 2024-07-17 18:05
> Thank you for your suggestions. I tried both options. Both options worked well.
> 

Good!

> Does this confirm that the issue is related to shared memory? Could you guide me on how to confirm or debug shared memory issues?

No, it is just a suspicion since the segfaults are triggered during init when first trying to touch. 

I just noticed - `mpiexec -n 182 ./hello-mpi` - Do you only have issue when launching more than 182 processes on the same node? If so, it is likely running out of shared memory. How much space do you have in `/dev/shm`?

**Comment by lrtfm** [comment] 2024-07-17 18:11
Yes. I run the command on a single node. I only have the issue when launching more than 182 processes.

The space of `/dev/shm`
```
[zzyang@math01 test]$ df -h
Filesystem           Size  Used Avail Use% Mounted on
devtmpfs             4.0M     0  4.0M   0% /dev
tmpfs                756G   85M  756G   1% /dev/shm
```
