### ISSUE TITLE
MPI_REAL16 reductions not correctly supported for Fortran programs

### ISSUE THREAD

**Issue by harisubramoni** [pmodels/mpich#4450] opened 2020-04-18 00:58 UTC
Hi,

This is an issue reported by our users. When doing a reduction using MPI_REAL16 in Fortran, the data seems to be getting lost in the conversion from Fortran to C (possibly due to differences in the real16 type in Fortran and the long double used to hold that on the C side).

On some debugging, what I observed was as follows

1. If the long double (say 'var') is interpreted as two doubles (var[0] and var[1]), then var[1] has the value set in the Fortran program.

2. If the long double (say 'var') is interpreted as such, then 'var' is being reported as 0 leading to the MPIR_SUM op not correctly incrementing the value.

Note that a similar program written in C using MPI_REAL16 works fine.

Details below.

Code details
=========
```
[subramon@haswell1 git]$ git branch
* (detached from v3.3.2)
  master

[subramon@haswell1 git]$ git remote -v
origin  https://github.com/pmodels/mpich (fetch)
origin  https://github.com/pmodels/mpich (push)
[test.f90.txt](https://github.com/pmodels/mpich/files/4495764/test.f90.txt)

```
Build details
========
```
/configure --prefix=/home/subramon/MPICH/git/install-dir CC=gcc CXX=g++ FC=gfortran F77=gfortran CFLAGS=-pipe --disable-gl --enable-g=all --enable-fast=none
```

Building Reproducer
=============
```
./bin/mpif90 -I./include -L./lib test.f90
```

Running Reproducer
==============
```
./bin/mpirun -n 2 -f hosts ./a.out

 voltq is   2.00000000000000000000000000000000000       in rank           0
 Calling reduce for voltq0 (16):
 voltq is   2.00000000000000000000000000000000000       in rank           1
 voltq0 (16):   2.00000000000000000000000000000000000
[subramon@haswell1 install-dir]$ vim test.f90
[subramon@haswell1 install-dir]$ ./bin/mpif90 -I./include -L./lib test.f90
[subramon@haswell1 install-dir]$
[subramon@haswell1 install-dir]$
[subramon@haswell1 install-dir]$ ./bin/mpirun -n 2 -f hosts ./a.out
 voltq is   2.00000000000000000000000000000000000       in rank           0
 voltd is   2.0000000000000000      in rank           0
 Calling reduce for voltd0 (8):
 voltq is   2.00000000000000000000000000000000000       in rank           1
 voltd is   2.0000000000000000      in rank           1
 Calling reduce for voltq0 (16):
 voltq0 (16):   2.00000000000000000000000000000000000
 voltd0 ( 8):   4.0000000000000000
```

Thx,
Hari.

**Comment by harisubramoni** [comment] 2020-04-18 00:59
This could be similar to https://github.com/pmodels/mpich/issues/258

**Comment by hzhou** [comment] 2020-04-20 13:53
@harisubramoni Could you upload the test program (`test.f90`)? I am slightly confused. You only mentioned this single fortran source, right? Where is the C side?

**Comment by harisubramoni** [comment] 2020-04-20 16:02
Hi, @hzhou .

Apologies. I thought I had uploaded the fortran program.

Frotran program

```
program testred16

use mpi_f08

implicit none

integer :: me,np
real(16) :: voltq,voltq0
real(8) :: voltd,voltd0
!
! initialize mpi and get the rank and total number of precesses
!
call mpi_init
call mpi_comm_rank(mpi_comm_world,me)
call mpi_comm_size(mpi_comm_world,np)
!
! determine total volume of active computational domain and send to the master
!
voltq = 2.0q0
voltd = 2.0d0
write(*,*) 'voltq is',voltq,'in rank',me
!write(*,*) 'voltd is',voltd,'in rank',me
voltq0 = 0.0q0
voltd0 = 0.0d0

!if(me.eq.0) then
!  write(*,*) 'Calling reduce for voltd0 (8):'
!endif
!call mpi_reduce(voltd,voltd0,1,mpi_real8, mpi_sum,0,mpi_comm_world)

if(me.eq.0) then
  write(*,*) 'Calling reduce for voltq0 (16):'
endif
call mpi_reduce(voltq,voltq0,1,mpi_real16,mpi_sum,0,mpi_comm_world)
if(me.eq.0) then
  write(*,*) 'voltq0 (16):',voltq0
!  write(*,*) 'voltd0 ( 8):',voltd0
endif

call mpi_finalize

end program
```
C Program
```
#include<mpi.h>
#include<stdio.h>

void main (int argc, char *argv[])
{
    int myid = -1, numprocs = -1;
    double src = 1.0, dst = 1.0;
    long double l_src = 1.0, l_dst = 1.0;

    MPI_Init(&argc, &argv);
    MPI_Comm_size(MPI_COMM_WORLD, &numprocs);
    MPI_Comm_rank(MPI_COMM_WORLD, &myid);

    MPI_Reduce(&src, &dst, 1, MPI_REAL8, MPI_SUM, 0, MPI_COMM_WORLD);
    if (myid == 0) {
        fprintf(stderr, "\nsrc = %f, dst = %f\n", src, dst);
    }
    MPI_Reduce(&l_src, &l_dst, 1, MPI_REAL16, MPI_SUM, 0, MPI_COMM_WORLD);
    if (myid == 0) {
        fprintf(stderr, "\nsrc = %Lf, dst = %Lf\n", l_src, l_dst);
    }
    MPI_Finalize();
    return;
}
```

**Comment by hzhou** [comment] 2020-04-20 18:19
Thanks @harisubramoni , I have reproduced error.

> This could be similar to #258

That issue is still open, does it mean we never fixed the issue? It looks like the case. Anyway, I looked into it, it appears FORTRAN does not simply pass `REAL16` type argument as a pointer to `long double`, so the buffer get miss-interpreted as soon as it enters C. We'll need to understand how exactly FORTRAN handle `REAL16` argument to hack the fix. Or we should try *gropp*'s suggestion in #258.

**Comment by hzhou** [comment] 2020-04-20 18:22
I am going to close #258 and use this issue to track instead. To make the referencing easier, I am duplicating the comment from #258 below:

> Originally by gropp on 2008-10-29 14:12:09 -0500

A possible fix for this is to use Fortran to process the Fortran-specific types, including REAL16 and COMPLEX32. The code might be faster as well.

What we might want to do is to change the way we invoke the routines for the predefined operations on the predefined types; we could have something like

if (predefinedop)
fcn = op->functionmap[datatype];
if (fcn) err = (*fcn)( ... ))
else err = opundefined

The "functionmap" will be a new field in the struct that MPI_Op refers to.

This preserves the lazy loading (executables only include the routines for the operations that are included). An additional benefit is that the operation codes might be faster - some compilers don't like to optimize big routines. It also can simplify supporting C++ types that might be added in MPI 2.2/3.0.

**Comment by hzhou** [comment] 2020-04-20 18:29
Wait, this is using `mpi_f08`, which definitely not the old issue is complaining.

**Comment by hzhou** [comment] 2020-04-20 18:41
With `use mpi` (F90), The program also fails -- probably the same issues as complained by #258 and #1770. However, the behavior has slight difference. With `use mpi`, it ended up with Segfault.

**Comment by hzhou** [comment] 2020-04-20 19:13
Value `1.0` is much more illuminating:

* with `f08`: `000000000000ffffffff3f0000000000000000`
* `use_mpi`: `000000000000ffffffff3f0000000002000000`
* `1.0` in C: `00000000000000ffffff80ffffffff3f000000000000`

**Comment by harisubramoni** [comment] 2020-04-20 19:50
Hi, @hzhou 

If you can point me to the portion of the code that generates the fortran bindings, I could also take a look at it.

Thx,
Hari.

**Comment by hzhou** [comment] 2020-04-20 20:08
> Hi, @hzhou
> 
> If you can point me to the portion of the code that generates the fortran bindings, I could also take a look at it.
> 
> Thx,
> Hari.

With `f90` and `f77`, I think it just directly links the fortran code to the C code, relying on the  calling convention. The generated binding code for `f90/f77` should be `src/binding/fortran/mpif_h/reducef.c`, generated by `buildiface` perl script in the same directory.

With `F08`, there are both a fortran part and c part and uses iso_c_binding to convert types in-between. The FORTRAN part is in `src/bindings/fortran/use_mod_f08/wrappers_f/reduce_f08ts.f90`. The C part is in `src/bindings/fortran/use_mpi_f08/wrappers_c/reduce_cdesc.c`.

**Comment by harisubramoni** [comment] 2020-04-20 20:24
Thanks!

**Comment by hzhou** [comment] 2020-04-20 22:55
Did some study, apparently `long double` is 16-byte in size, but in binary a 10-byte floating point.

**Comment by harisubramoni** [comment] 2020-04-20 23:06
Hi,

Does this ring any bells?

https://software.intel.com/en-us/forums/intel-fortran-compiler/topic/267926
```
1. The C long double type is an 80-bit extended type that is not compatible with Fortran's REAL*16.
```

**Comment by hzhou** [comment] 2020-04-21 00:49
> 
> 
> Hi,
> 
> Does this ring any bells?
> 
> https://software.intel.com/en-us/forums/intel-fortran-compiler/topic/267926
> 
> ```
> 1. The C long double type is an 80-bit extended type that is not compatible with Fortran's REAL*16.
> ```

Yes, it confirms my suspicion :smiley:

I think here is a potential solution (a version of *gropp*'s comment): At initialization, fortran register a set of "op" functions to C for a set of fortran-specific datatypes, and we call them in `MPIR_op`s when the datatype is in this fortran specific group.

**Comment by harisubramoni** [comment] 2020-04-21 01:25
> > Hi,
> > Does this ring any bells?
> > https://software.intel.com/en-us/forums/intel-fortran-compiler/topic/267926
> > ```
> > 1. The C long double type is an 80-bit extended type that is not compatible with Fortran's REAL*16.
> > ```
> 
> Yes, it confirms my suspicion 😃
> 
> I think here is a potential solution (a version of _gropp_'s comment): At initialization, fortran register a set of "op" functions to C for a set of fortran-specific datatypes, and we call them in `MPIR_op`s when the datatype is in this fortran specific group.

That sounds like a good option to me :-). Can you please let me know if I can help in anyway to come up with a patch?

**Comment by hzhou** [comment] 2020-04-21 13:59
> That sounds like a good option to me :-). Can you please let me know if I can help in anyway to come up with a patch?

A quick patch can be: create an `src/binding/fortran/mpif_h/fortran_ops.f`, inside which define subroutines such as `real16_sum(A, B, N)`, `real16_prod(A, B, N)`, etc. Add this file into `mpi_sources` (in `Makefile.mk`). That will make these routines available for the MPICH's C part to call.

For the C part, in `src/include/mpir_op_util.h`, remove `MPI_REAL16` from the `FLOATING_POINT_EXTRA` groups; in `src/mpi/coll/op/opsum.c`, Add
```
    case MPI_REAL16:
         real16_sum_(invec, inoutvec, Len);
         break;
```
to function `MPIR_SUM` right above the default case, and add
```
    case MPI_REAL16:
```
to function `MPIR_SUM_check_dtype` right above `return MPI_SUCCESS;`.

This should work but hacky. For one, we just added another fortran object into `libmpi.so`. For two, we may like to come up with some generalized handling that are consistent with the rest of the code.

To move the fortran object to `libmpi_fortran.so`, we'll need some function table on the C side and have `mpirinitf` to regiester these fortran op functions at init time. Not difficult, but take time to design and probably will bring some refactoring as well. This is probably the proper way, but it will take some time.

@harisubramoni If you are ok with quich hacky patch, I can quickly put up a draft PR for you. For proper PR, I have to put it on a TODO list :)

**Comment by hzhou** [comment] 2020-04-21 14:19
@harisubramoni I created a draft PR as a demonstration of how this may work. The proper PR will take a while (due to priorities).

**Comment by hzhou** [comment] 2020-04-21 15:34
> On a separate note, wouldn't similar changes be required

**Comment by hzhou** [comment] 2020-04-21 15:34
> On a separate note, wouldn't similar changes be required

**Comment by harisubramoni** [comment] 2020-04-21 16:07
> > On a separate note, wouldn't similar changes be required

Hi, @hzhou 

Could you please let me know how the new file `fortran_ops.f` gets linked in? I am not sure if I am missing anything here.

Thx,
hari.

**Comment by harisubramoni** [comment] 2020-04-21 16:12
Hi, @hzhou

Could you please let me know how the new file `fortran_ops.f` get linked in? Am I missing something here?

Thx,
Hari.

**Comment by hzhou** [comment] 2020-04-21 16:30
> On a separate note, wouldn't similar changes be required for all the Ops?

Yes. :wink: 

> Could you please let me know how the new file fortran_ops.f gets linked in? I am not sure if I am missing anything here.

I missed something. Now added :wink:  `Makefile.mk` is generated by `buildiface` script, so need patch `buildiface`.

PS: sorry for the delay. Typing messages in the middle of a github outage, I almost thought I caused the heavoc :smile: 

PS2: for questions regarding the patch, we should discuss in the PR #4454.

**Comment by harisubramoni** [comment] 2020-04-21 16:38
Hi, @hzhou 

Thanks! I did not realize github was down. I was trying to comment in the PR, but it did not allow me. Then, I tried here. I guess when github came up, this one was still in process.

Let me move to the PR for further discussion.

Thx,
Hari.

**Closed** 2020-10-13 14:58 UTC
