### ISSUE TITLE
4.2.0rc1 with (default) ch4 on macOS hangs during MPI_Finalize()

### ISSUE THREAD

**Issue by eborisch** [pmodels/mpich#6856] opened 2023-12-20 22:35 UTC
Similar to #6584, but in MPI_Finalize().

Reproducer:
```c
#include <stdio.h>
#include <mpi.h>

int main(int argc, char** argv)
{
    MPI_Init(&argc, &argv);
    MPI_Barrier(MPI_COMM_WORLD); /* Fails with or without */
    printf("HERE\n");
    MPI_Finalize();
    return 0;
}
```

Fails: 
```
$ mpiexec -np 2 ./minimal
HERE
HERE
Abort(811174031): Fatal error in internal_Finalize: Other MPI error, error stack:
internal_Finalize(47997).........: MPI_Finalize failed
MPII_Finalize(455)...............:
MPID_Finalize(775)...............:
MPIDI_OFI_mpi_finalize_hook(1081):
flush_send_queue(1040)...........:
MPIDI_OFI_handle_cq_error(790)...: OFI poll failed (ofi_events.c:790:MPIDI_OFI_handle_cq_error:Input/output error)
Abort(811174031): Fatal error in internal_Finalize: Other MPI error, error stack:
internal_Finalize(47997).........: MPI_Finalize failed
MPII_Finalize(455)...............:
MPID_Finalize(775)...............:
MPIDI_OFI_mpi_finalize_hook(1081):
flush_send_queue(1040)...........:
MPIDI_OFI_handle_cq_error(790)...: OFI poll failed (ofi_events.c:790:MPIDI_OFI_handle_cq_error:Input/output error)```
```

Works if I set FI_PROVIDER=tcp :
```sh
$ FI_PROVIDER=tcp mpiexec -np 2 ./minimal
HERE
HERE
```

```
$ mpichversion
MPICH Version:      4.2.0rc1
MPICH Release date: Wed Dec 13 12:13:53 CST 2023
MPICH ABI:          0:0:0
MPICH Device:       ch4:ofi
MPICH configure:    --prefix=/opt/local --disable-dependency-tracking --enable-fortran --disable-silent-rules --enable-base-cache --enable-cache --enable-cxx --enable-fast=all --enable-shared --enable-versioning --with-pm=hydra --with-hwloc=/opt/local --libdir=/opt/local/lib/mpich-clang17 --sysconfdir=/opt/local/etc/mpich-clang17 --program-suffix=-mpich-clang17 --includedir=/opt/local/include/mpich-clang17 MPICHLIB_CFLAGS=-pipe -march=native -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -arch x86_64 CFLAGS= MPICHLIB_CPPFLAGS=-isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk CPPFLAGS= MPICHLIB_CXXFLAGS=-pipe -march=native -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -arch x86_64 CXXFLAGS= MPICHLIB_FFLAGS=-pipe -fallow-argument-mismatch -m64 FFLAGS= MPICHLIB_FCFLAGS=-pipe -fallow-argument-mismatch -m64 FCFLAGS=
MPICH CC:           /opt/local/bin/clang-mp-17  -pipe -march=native -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -arch x86_64 -fno-common  -DNDEBUG -DNVALGRIND -O2
MPICH CXX:          /opt/local/bin/clang++-mp-17  -pipe -march=native -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -arch x86_64 -DNDEBUG -DNVALGRIND -O2
MPICH F77:          /opt/local/bin/gfortran-mp-13  -pipe -fallow-argument-mismatch -m64 -O2
MPICH FC:           /opt/local/bin/gfortran-mp-13  -pipe -fallow-argument-mismatch -m64 -O2
MPICH features:     threadcomm
```

**Comment by eborisch** [comment] 2024-02-02 18:12
Still the case with rc3.

**Comment by raffenet** [comment] 2024-02-02 18:38
Could you also set `MPIR_CVAR_DEBUG_SUMMARY=1` in the execution environment and paste the output?

**Comment by eborisch** [comment] 2024-02-03 04:56
Apologies; I had too many different versions installed. 4.2.0rc3 appears to be working for me.

**Comment by eborisch** [comment] 2024-02-05 22:29
So this isn't completely gone, after all. Turns out it is the presence of my VPN connection that makes ch4 fail. (Works when VPN not connected; ch3 works all the time.)

When I'm connected to VPN, I get the VPN connection showing up in the debug summary ([+] is with VPN connected):

```
 ==== Various sizes and limits ====
 sizeof(MPIDI_per_vci_t): 256
 Required minimum FI_VERSION: 0, current version: 10012
+provider: tcp, score = 4, pref = 0, FI_SOCKADDR_IN [16] 10.<A>.<B>.<C>
 provider: tcp, score = 4, pref = 0, FI_SOCKADDR_IN [16] 10.0.1.73

[...] Multiple other instances of the extra address, including:

 provider: sockets, score = 3, pref = 0, FI_SOCKADDR_IN6 [28] ::1
+provider: sockets, score = 5, pref = 0, FI_SOCKADDR_IN [16] 10.132.226.233
 provider: sockets, score = 5, pref = 0, FI_SOCKADDR_IN [16] 10.0.1.73

[...]

 provider: sockets, score = 5, pref = 0, FI_SOCKADDR_IN6 [28] ::1
 Required minimum FI_VERSION: 10005, current version: 10012
 ==== Capability set configuration ====
-libfabric provider: sockets - 10.0.1.0/24
+libfabric provider: sockets - 10.<A>.<B>.<C>/32
 MPIDI_OFI_ENABLE_DATA: 1
 MPIDI_OFI_ENABLE_AV_TABLE: 1
 MPIDI_OFI_ENABLE_SCALABLE_ENDPOINTS: 1
```

This is picking up the VPN utun0 connection:

```
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1375
	inet 10.<A>.<B>.<C> --> 1.1.1.1 netmask 0xffffffff
	nd6 options=201<PERFORMNUD,DAD>
```

And then failing:
```
Abort(811174031): Fatal error in internal_Finalize: Other MPI error, error stack:
internal_Finalize(47997).........: MPI_Finalize failed
MPII_Finalize(421)...............:
MPID_Finalize(775)...............:
MPIDI_OFI_mpi_finalize_hook(1081):
flush_send_queue(1040)...........:
MPIDI_OFI_handle_cq_error(790)...: OFI poll failed (ofi_events.c:790:MPIDI_OFI_handle_cq_error:Input/output error)
```

Any suggestions on how to avoid this error with ch4?

**Comment by hzhou** [comment] 2024-02-05 22:48
@eborisch Could you try set environment `FI_PROVIDER=tcp` ?

**Comment by eborisch** [comment] 2024-02-08 00:04
Works great with `FI_PROVIDER=tcp`.

**Comment by lindsayad** [comment] 2024-02-29 16:54
Idaho National Laboratory just went to 100% time enforcement of zscaler, and so this issue will be cropping up for a lot of MOOSE users. Is the `FI_PROVIDER` environment flag the permanent solution?

**Comment by hzhou** [comment] 2024-02-29 17:07
We haven't been able to reproduce the issue locally. Please add comments if you continue to have issues. Manually setting `FI_PROVIDER` works but it will prevent it to use better provider if the system has higher-bandwidth interconnect than `tcp`.

**Comment by lindsayad** [comment] 2024-02-29 18:39
Thanks for the rapid reply @hzhou. I will definitely update this issue if/when I learn more

**Comment by hzhou** [comment] 2024-04-10 20:47
Closing this issue due to lack of updates. Feel free to re-open if there is updates or continuing issues.

**Closed by hzhou** 2024-04-10 20:47 UTC

**Comment by zjibben** [comment] 2024-06-06 18:48
I'm hitting this issue on MPICH 4.2.1, MacOS 14.5 Sonoma. LANL just transitioned to zscaler, which sounds like it might be the issue based on earlier comments. The `FI_PROVIDER=tcp` workaround is working, but I'm not sure how much this affects the performance for my application. I can provide more details if you like.

**Comment by lindsayad** [comment] 2024-06-06 19:41
Hopefully LANL and INL networks teams can work with the mpich team to figure this out. Thus far our (INL) networks team hasn't expressed much interest to my disappointment. I might press them again now that we have your report @zjibben

**Comment by hzhou** [comment] 2024-06-06 19:49
Try enable `MPIR_CVAR_DEBUG_SUMMARY=1` and run a basic MPI test program (e.g. `MPI_Init` then `MPI_Finalize`). It should tell you which provider it is using by default. If the default is `sockets` provider, then `tcp` provider should perform better and generally safe to switch. We haven't preferred `tcp` over `sockets` due to some of the RMA ordering issues. But we don't expect many applications will encounter issues.

If the default is not `sockets` provider and you are seeing "similar" issues, please report. They may be "similar" on look, but the actual causes are often provider-specific.

**Comment by lindsayad** [comment] 2024-06-06 21:27
I assume this is saying we're using sockets?
```
==== Capability set configuration ====
libfabric provider: sockets - 100.64.0.0/16
```

**Comment by hzhou** [comment] 2024-06-06 21:53
> I assume this is saying we're using sockets?
> 
> ```
> ==== Capability set configuration ====
> libfabric provider: sockets - 100.64.0.0/16
> ```

Yes

**Comment by zjibben** [comment] 2024-06-08 13:14
Same case on my end.

- If I set `FI_PROVIDER=sockets` or leave it unset, then my simple MPI program hangs on finalize, but only if zscaler is running. I see an output like:

```
libfabric provider: sockets - 100.64.0.0/16
```

- If I set `FI_PROVIDER=tcp` the program completes, no issues.

```
libfabric provider: tcp - 100.64.0.0/16
```

- If zscaler is completely closed down then either works fine.
