### ISSUE TITLE
build: compiling MPICH with f18

### ISSUE THREAD

**Issue by coti** [pmodels/mpich#4417] opened 2020-03-27 07:46 UTC
Hello,

I am trying to compile MPICH 3.3.2 using f18 as its Fortran compiler. I am using gfortran 8.1.0 as its backend compiler.

I am configuring MPICH with:
```
export F18_FC=`which gfortran`
/configure --prefix=$PWD/build CC=`which clang` CXX=`which clang++` F77=`which f18` FC=`which f18`
```
And I can check that:
```
$ $F18_FC --version
GNU Fortran (GCC) 8.1.0
```

When I compile, I get the following error:
```
  MOD      src/binding/fortran/use_mpi/mpi_base.mod-stamp
/tmp/f18-2be6e.f90:64:9:

    USE :: mpi_constants, ONLY: mpi_address_kind
         1
Fatal Error: File 'mpi_constants.mod' opened at (1) is not a GNU Fortran module file
compilation terminated.
```
Which is strange, because I read [here](https://gcc.gnu.org/bugzilla/show_bug.cgi?format=multiple&id=59276) that this error message is given by gfortran 4.8 when it is trying to read a module that was compiled with a different (more recent) version of gfortran, and more recent versions of gfortran give a different error message. 

There is a gfortran 4.8 installed somewhere on my machine
```
$ /usr/bin/gfortran --version
GNU Fortran (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
```
but I thought I had configured the compilation such in a way that make was not supposed to use it.

* Did I miss a flag somewhere?

Apparently, the error comes from a module called  ```mpi_constants.mod```. I have to files named like this, and ```file``` does not give the same thing for them:
```
$ find . -name "mpi_constants.mod"
./src/binding/fortran/use_mpi/mpi_constants.mod
./mpi_constants.mod
$ file ./src/binding/fortran/use_mpi/mpi_constants.mod
./src/binding/fortran/use_mpi/mpi_constants.mod: C source, UTF-8 Unicode (with BOM) text
$ file ./mpi_constants.mod
./mpi_constants.mod: C source, UTF-8 Unicode (with BOM) text
```

The command that fails is:
```
/bin/sh ./libtool --silent --tag=FC   --mode=compile $F18_FC -Isrc/binding/fortran/use_mpi  -O2 -Jsrc/binding/fortran/use_mpi -c src/binding/fortran/use_mpi/mpi_base.f90 -o src/binding/fortran/use_mpi/mpi_base.lo
```
If I remove the mpi_constants.mod located in the current directory (to make sure the compiler is using the other one), if works. But then when I call ```make``` again, I get a lot of errors like the following one:
```
  MOD      src/binding/fortran/use_mpi/mpi_base.mod-stamp
src/binding/fortran/use_mpi/mpi_base.f90:77:16: error: Error reading module file for module 'mpi_constants'
             USE MPI_CONSTANTS,ONLY:MPI_ADDRESS_KIND
                 ^^^^^^^^^^^^^
src/binding/fortran/use_mpi/mpi_base.f90:77:16: #�: unknown or unimplemented directive
             USE MPI_CONSTANTS,ONLY:MPI_ADDRESS_KIND
                 ^^^^^^^^^^^^^
```
So I guess it was not the right thing to do and there are other problems.

* So, I think my problem is that a wrong version of gfortran is called somewhere: did I forget a configuration parameter somewhere?
* Or is it another problem?

Thanks a lot.

**Comment by hzhou** [comment] 2020-03-28 03:05
@coti Could you attach `config.log` and maybe the generated `Makefile`?

**Comment by coti** [comment] 2020-03-28 03:25
Sure! Thank you for your reply. Here they are. GitHub refused to upload a file called Makefile so I have renamed it as Makefile.txt.

[config.log](https://github.com/pmodels/mpich/files/4396562/config.log)
[Makefile.txt](https://github.com/pmodels/mpich/files/4396563/Makefile.txt)

**Comment by eugeneswalker** [comment] 2020-03-30 20:41
I am seeing this same error, except I am using `gfortran 7.3.0` as the backend for `f18`

**Comment by hzhou** [comment] 2020-03-30 20:55
Thanks @eugeneswalker for the additional data point. It probably due to `libtool` heuristics breaks down because it does not recognize `f18`. I'll investigate it later.

**Comment by raffenet** [comment] 2020-03-30 21:25
This was fixed in master, but not in the 3.3.x branch. https://github.com/pmodels/mpich/pull/4164

**Comment by eugeneswalker** [comment] 2020-03-30 21:58
> This was fixed in master, but not in the 3.3.x branch. #4164

Other than using master, is there anything else that needs to be done to take advantage of this fix? I just tried with a checkout of mpich@master and I actually get the same error. @raffenet

**Comment by raffenet** [comment] 2020-03-31 15:14
Hmm, I did not have any issue when testing on Debian (buster and bullseye). I have not tested on RedHat, but can do some experiments. Is it possible to share your container image @eugeneswalker?

**Comment by eugeneswalker** [comment] 2020-03-31 16:49
@raffenet The image is called `ecpe4s/mpich-f18-debug:latest` and it is now on Docker Hub.

It is using:
* Spack 0.14.1 to drive the builds, setup the build environments, and manage dependencies
* Ubuntu 18.04 - x86_64
* Clang 9.0.1 w/ F18

The way I am kicking off the mpich build is with Spack:
```
$> export F18_FC=`spack location -i gcc@7.3.0`/bin/gfortran
$> spack install -j<parallelism> mpich@develop%clang
```
Specifying `mpich@develop` just tells Spack to checkout master branch. The build proceeds for quite some time, and when it ultimately fails you can do:
```
$> cd `spack location -s mpich`
```

to get to the path Spack uses to stage the mpich build.

The following files will be available at the location given by `spack location -s mpich`:

* `spack-build-out.txt` -- build log
* `spack-build-env.txt` -- the value of all environment variables set during mpich build
* `spack-src/` -- directory which contains git checkout of mpich

Thank you for taking a look!

**Comment by eugeneswalker** [comment] 2020-04-03 17:11
I tried building this time with llvm+f18 built a bit differently and managed to get to this point during `make`  stage for 'mpich@develop':

```
$> make -j32
...
  GEN      lib/libmpi.la
  MOD      src/binding/fortran/use_mpi/mpi_constants.mod-stamp
  MOD      src/binding/fortran/use_mpi/mpi_sizeofs.mod-stamp
  MOD      src/binding/fortran/use_mpi/mpi_base.mod-stamp
  MOD      src/binding/fortran/use_mpi/mpi.mod-stamp
gfortran: error: libmpi.so.0: No such file or directory
gfortran: error: unrecognized command line option '--whole-archive'; did you mean '--whole-file'?
gfortran: error: unrecognized command line option '--no-whole-archive'; did you mean '--no-whole-file'?
gfortran: error: unrecognized command line option '-soname'
Makefile:20375: recipe for target 'lib/libmpi.la' failed
make[2]: *** [lib/libmpi.la] Error 1
make[2]: Leaving directory '/mpich-src'
Makefile:45618: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/mpich-src'
Makefile:13617: recipe for target 'all' failed
make: *** [all] Error 2
```


@raffenet

**Comment by eugeneswalker** [comment] 2020-04-04 05:43
I can at least get a static library with configure options `--enable-static --disable-shared` ...

**Comment by eugeneswalker** [comment] 2020-04-04 20:03
Related issue from 2018: https://github.com/pmodels/mpich/issues/3334 @raffenet @naromero77 @coti

**Comment by eugeneswalker** [comment] 2020-04-05 17:18
It looks like part of the problem is that the libtool script is not setting the value of `wl` correctly for `FC` tag. For instance, instead of `-Wl,--whole-archive` libtool is just doing `--whole-archive`. Likewise, instead of `-Wl,-soname` it is doing `-soname`. Likewise libtool is not setting the PIC flag correctly for tag `FC`. If I manually edit the libtool script so that `-Wl,` and `-fPIC` are added correctly, then we get here:

```
$> make
...
gfortran: warning: lib/.libs/libmpi.so: linker input file unused because linking not done
gfortran: warning: /opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.5.0/gcc-7.3.0-tfwxqfxrsgb3hagoaehdnjz2qwojhsrb/lib/../lib64/libgfortran.so: linker input file unused because linking not done
gfortran: warning: /opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.5.0/gcc-7.3.0-tfwxqfxrsgb3hagoaehdnjz2qwojhsrb/lib/../lib64/libquadmath.so: linker input file unused because linking not done
gfortran: error: libmpi.o: No such file or directory
gfortran: error: libgfortran.o: No such file or directory
gfortran: error: libquadmath.o: No such file or directory
Makefile:17211: recipe for target 'lib/libmpifort.la' failed
make[2]: *** [lib/libmpifort.la] Error 1
make[2]: Leaving directory '/mpich-src'
Makefile:45618: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/mpich-src'
Makefile:13617: recipe for target 'all' failed
make: *** [all] Error 2
```

The link command that gives this error is large, but if I change the parts involving `libmpi.so`, `libgfortran.so` and `libquadmath.so` from this form:
```
link line: /opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.5.0/gcc-7.3.0-tfwxqfxrsgb3hagoaehdnjz2qwojhsrb/lib/../lib64/libquadmath.so
```

to this form:
```
link line: -L/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.5.0/gcc-7.3.0-tfwxqfxrsgb3hagoaehdnjz2qwojhsrb/lib/../lib64/ -lquadmath
```

And the link looks like it succeeds. Any thoughts? @raffenet @coti

**Comment by raffenet** [comment] 2020-04-07 19:21
> It looks like part of the problem is that the libtool script is not being setup correctly. For instance, for FC `wl=''` in `libtool` so that instead of `-Wl,--whole-archive` libtool is just doing `--whole-archive` during linking. Likewise, instead of `-Wl,-soname` it is doing `-soname`. The PIC flag is also not being set correctly for FC. If I manually edit the libtool script so that `-Wl,` and `-fPIC` are added correctly, then we get here:

`libtool` is setup correctly in my experiments with the container image you provided. I am working with the MPICH master branch directly cloned from Github. Without #4164, then I would expect to see `libtool` setup incorrectly as you describe.

I do run into Fortran module issue @coti posted, and will continue to investigate.

**Comment by raffenet** [comment] 2020-04-07 20:30
FWIW, I failed to build this simple module example with `f18`.

http://fortranwiki.org/fortran/show/Compiling+and+linking+modules

 It works fine with `gfortran`.

**Comment by eugeneswalker** [comment] 2020-04-07 20:38
Are you saying you successfully compiled mpich@master with f18+llvm in that container? Did you set any environment variables other than CC, CXX, FC, F77, and F18_FC? The configure script just worked out of the box?

**Comment by eugeneswalker** [comment] 2020-04-07 21:01
> FWIW, I failed to build this simple module example with `f18`.
> 
> http://fortranwiki.org/fortran/show/Compiling+and+linking+modules
> 
> It works fine with `gfortran`.

With `f18` I believe you should be using `-Mfree` instead of `-ffree-fortran` as suggested in the link you reference.

**Comment by raffenet** [comment] 2020-04-07 21:05
> > FWIW, I failed to build this simple module example with `f18`.
> > http://fortranwiki.org/fortran/show/Compiling+and+linking+modules
> > It works fine with `gfortran`.
> 
> With `f18` I believe you should be using `-Mfree` instead of `-ffree-fortran` as suggested in the link you reference.

```
root@678bc5ea5371:~/mpich# f18 -Mfree -c testModule.f mainProg.f
mainProg.f:2:7: error: Error reading module file for module 'mathmodule'
    use mathModule
        ^^^^^^^^^^
mainProg.f:2:7: File has invalid checksum: ./mathmodule.mod
    use mathModule
        ^^^^^^^^^^
mainProg.f:5:19: error: No explicit type declared for 'pi'
    print *, "pi:", pi, "e:", e, "gamma:", gamma
                    ^^
mainProg.f:5:29: error: No explicit type declared for 'e'
    print *, "pi:", pi, "e:", e, "gamma:", gamma
                              ^
mainProg.f:5:42: error: No explicit type declared for 'gamma'
    print *, "pi:", pi, "e:", e, "gamma:", gamma
                                           ^^^^^
f18: semantic errors in mainProg.f
```

**Comment by raffenet** [comment] 2020-04-07 21:09
> Are you saying you successfully compiled mpich@master with f18+llvm in that container? Did you set any environment variables other than CC, CXX, FC, F77, and F18_FC? The configure script just worked out of the box?

No, I was not successful. I am running into the same module issue that @coti posted. Given my experiment with a simple test module, I suspect the problem is not in MPICH.

**Comment by eugeneswalker** [comment] 2020-04-07 21:15
Unfortunately the Spack-built version of f18 in `ecpe4s/mpich-f18-debug:latest` is not functional in some key respects. I did not know that when I posted it originally. However, that said, I have a new container on Docker Hub with f18 built outside of Spack, where this f18 CAN compile and link the module example you mention, as well as some other examples I have tested. The container is called `ecpe4s/f18:latest`.

```
# here using the f18 wrapper script called flang
$> flang -Mfree -c testModule.f mainProg.f
$> flang testModule.o mainProg.o
$> ./a.out
 pi:   3.14150000     e:   2.71830010     gamma:  0.577220023
```

I apologize for the fake out with the first container. This is a learning experience for me. Thank you for taking a look. @raffenet

**Comment by raffenet** [comment] 2020-04-08 18:53
I get this error when building the simple module example with `ecpe4s/mpich-f18-debug:latest`.

```
root@e9d7739fe362:~/mod-example# f18 -Mfree -c testModule.f mainProg.f

fatal internal error: CHECK(source.back() == '\n' && "missing ultimate newline") failed at /f18-src/lib/Parser/source.cpp(26)
Aborted
```

**Comment by eugeneswalker** [comment] 2020-04-08 18:55
> I get this error when building the simple module example with `ecpe4s/mpich-f18-debug:latest`.
> 
> ```
> root@e9d7739fe362:~/mod-example# f18 -Mfree -c testModule.f mainProg.f
> 
> fatal internal error: CHECK(source.back() == '\n' && "missing ultimate newline") failed at /f18-src/lib/Parser/source.cpp(26)
> Aborted
> ```

yes but like i said in my last post, the f18 is no good in that image. i apologize. the new image is ecpe4s/f18 and it does run the examples you linked to. i describe it in my last post. it also runs other basic fortran moi examples like ring and matmult.

**Comment by raffenet** [comment] 2020-04-08 18:56
Sorry, I meant the latest image. Copy/pasted the wrong text.

**Comment by raffenet** [comment] 2020-04-08 19:09
Just to confirm, this is now the location of `f18` that produces the new error.

```
root@e9d7739fe362:~/mod-example# which f18
/f18/bin/f18
```

**Comment by eugeneswalker** [comment] 2020-04-08 19:17
You have to either use the wrapper script for f18, which is called `flang` and which is in the PATH, OR you have to manually add the arguments which the `flang` wrapper script adds for you. That is why I am using `flang` in the following snippet (it is just wrapping f18 and adding arguments which tell f18 where fortran intrinsics are and what the module suffix should be):

```
# here using the f18 wrapper script called flang
$> flang -Mfree -c testModule.f mainProg.f
$> flang testModule.o mainProg.o
$> ./a.out
 pi:   3.14150000     e:   2.71830010     gamma:  0.577220023
```

@raffenet

**Comment by raffenet** [comment] 2020-04-08 20:16
Ah, OK. Then we are back to the libtool problem. Time to figure out why this configuration is not recognized...

**Comment by eugeneswalker** [comment] 2020-04-08 20:23
I do not know much about how the rules are constructed for generating `libtool` BUT I was looking at what you did with https://github.com/pmodels/mpich/pull/4164 and I tried to verify that the patched case condition was being matched (From libtool.m4), and I think it may not be being caught. I was thinking this may be because:

```
$> flang -V
f18 compiler (under development)
```

I think the libtool generation rules may be relying on more appropriate, complete output from the version flag as is normally provided:

```
$> gfortran -v
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

$> clang -v
clang version 11.0.0 (https://github.com/flang-compiler/f18-llvm-project.git b3cc5dcef0f29f166fe33022858205a1243abd80)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /llvm/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Candidate multilib: .;@m64
Selected multilib: .;@m64

$> gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
```

I really don't know though. Thanks for working on this!

**Comment by raffenet** [comment] 2020-04-10 20:43
Another update: I found that if I use the system autoconf/automake/libtool, then the resulting libtool script generated by configure correctly recognized `flang`. I don't 100% know why the Spack autotools installation does not work. I suspect `libtool.m4` is being replaced somewhere during configure, possible because of the separate installation directory for each that MPICH warns about in `autogen.sh`.

Now I get to the error in https://github.com/pmodels/mpich/issues/4417#issuecomment-609450566 and will need to keep investigating.

**Comment by raffenet** [comment] 2020-04-11 02:05
I think the wrapper script might be causing issues during linking. I made a simple example where I attempt to link a Fortran program with a C object file. This mimics the mixed C/Fortran libraries of MPICH.
```
foo.c
---
void foo(int bar) {
  return;
}
```
```
hello.f90
---
program helloworld
print *, "Hello world!"
end program helloworld
```
First compile the C file.
```
root@8f4faa7b11d8:~# gcc -c foo.c
```
The flang script fails to link with the same error we saw before.
```
root@8f4faa7b11d8:~# flang hello.f90 foo.o
gfortran: warning: /f18/include/flang: linker input file unused because linking not done
/usr/bin/ld: cannot find /f18/include/flang: File format not recognized
collect2: error: ld returned 1 exit status
```
While using f18 has no problem.
```
root@8f4faa7b11d8:~# f18 hello.f90 foo.o
root@8f4faa7b11d8:~# ./a.out
 Hello world!
```

**Comment by eugeneswalker** [comment] 2020-04-11 03:29
Actually those steps worked for me:
```
$> gcc -c foo.c
$> flang hello.f90 foo.o
$> ./a.out
Hello World
```
I'm using `ecpe4s/f18:latest` ...

**Comment by naromero77** [comment] 2020-04-11 04:05
@eugeneswalker Are you using the flang which is a wrapper script or the real thing? (from what has been merged into LLVM upstream)

**Comment by naromero77** [comment] 2020-04-11 04:14
Ignore my last comment -- even though f18 has been merged into LLVM upstream, it hasn't been combined with the LLVM backend yet.

**Comment by naromero77** [comment] 2020-04-11 04:23
@eugeneswalker @raffenet I tried Ken's test using f18 compiled via Spack and I am getting a different issue.
```
naromero@naromero-desktop linking]$ flang hello.f90 foo.o
/scratch/naromero/opt/spack/linux-ubuntu18.04-westmere/gcc-7.4.0/binutils-2.34-meoo26xojajgalyw3w65eqqwubdyh2m3/bin/ld: cannot find -lpthread
[naromero@naromero-desktop linking]$ f18 hello.f90 foo.o
/scratch/naromero/opt/spack/linux-ubuntu18.04-westmere/gcc-7.4.0/binutils-2.34-meoo26xojajgalyw3w65eqqwubdyh2m3/bin/ld: cannot find -lpthread
```

**Comment by naromero77** [comment] 2020-04-11 04:36
OK, I got it to work this time. It was picking up the wrong linker `ld`.
```
naromero@naromero-desktop linking]$ flang hello.f90 foo.o
[naromero@naromero-desktop linking]$ f18 hello.f90 foo.o
[naromero@naromero-desktop linking]$ which f18
/scratch/naromero/opt/spack/linux-ubuntu18.04-westmere/gcc-7.4.0/f18-master-c7xjwrfxsjy5rromwzqu5mwpkya5gbzy/bin/f18
[naromero@naromero-desktop linking]$ which ld
/usr/bin/ld
```

**Comment by naromero77** [comment] 2020-04-11 04:36
I will try this with the PGI backend for f18 over the weekend.

**Comment by eugeneswalker** [comment] 2020-04-11 04:52
> @eugeneswalker Are you using the flang which is a wrapper script or the real thing? (from what has been merged into LLVM upstream)

The f18 built in docker image `ecpe4s/f18` is from https://github.com/flang-compiler/f18 and the llvm is from https://github.com/flang-compiler/f18-llvm-project. So I am using the flang wrapper script for f18, not the actual flang :) I know you said to ignore your comment but just wanted to be clear for anyone else. I did get mpich built to build, with some manual+surgical modifications to the generated `libtool` script. I'm able to compile some simple C and Fortran MPI codes like ring and matmult using mpich+f18+llvm. I don't know how to fix the generation rules so that `libtool` gets correctly generated in the first place. Ordered a book on Autotools+Libtool to see if I can learn something useful. @naromero77

**Comment by raffenet** [comment] 2020-04-13 17:20
> Actually those steps worked for me:
> 
> ```
> $> gcc -c foo.c
> $> flang hello.f90 foo.o
> $> ./a.out
> Hello World
> ```
> 
> I'm using `ecpe4s/f18:latest` ...

I recreated my container from scratch and had no issue either, so I guess it must have been something in my environment. Here is another test that I think better matches the problem during MPICH build. If I just add a single shared library via filename (as opposed to `-l<libname>`), something goes wrong.

```
root@5419959d8ef3:~# flang hello.f90 /usr/lib/x86_64-linux-gnu/librt.so
gfortran: warning: /usr/lib/x86_64-linux-gnu/librt.so: linker input file unused because linking not done
gfortran: error: librt.o: No such file or directory
```
```
root@5419959d8ef3:~# f18 hello.f90 /usr/lib/x86_64-linux-gnu/librt.so
gfortran: warning: /usr/lib/x86_64-linux-gnu/librt.so: linker input file unused because linking not done
gfortran: error: librt.o: No such file or directory
```
```
root@5419959d8ef3:~# gfortran hello.f90 /usr/lib/x86_64-linux-gnu/librt.so
root@5419959d8ef3:~# ./a.out
 Hello world!
```

**Comment by hzhou** [comment] 2022-01-19 06:00
I am linking this issue with PR#5771, as I tested there with `f18` compiler, and it works fine. The issue is probably fixed earlier.

**Comment by hzhou** [comment] 2022-01-19 16:04
The compilation produces both `mpi_constants.mod` and `mpi_constants.f18.mod`. It appears `f18` need the latter but loaded the former. Is there any specific flag to instruct it?

**Comment by hzhou** [comment] 2022-01-19 16:18
I am marking this issue as `wontfix` since it appears to me an issue on the `f18` side -- it can't consistently create `.mod` and load them. I am tested this with LLVM-13.0 release tag. 
@coti @eugeneswalker @naromero77 Do you think there is something we should do on the MPICH side?

**Comment by hzhou** [comment] 2022-07-16 02:49
Close issue due to stale and lack of response.

**Closed by hzhou** 2022-07-16 02:49 UTC
Labels: wontfix
