### ISSUE TITLE
bug: coll: MPI_Alltoall Performance Degradation

### ISSUE THREAD

**Issue by pavanbalaji** [pmodels/mpich#2530] opened 2017-02-06 23:25 UTC
The performance of MPI_Alltoall seems to be very sensitive to the number of processes.  The below numbers were reported by Jayesh Krishna.

```
====================================================================
===================== MPICH+36procs/node+10nodes =======================
# OSU MPI All-to-All Personalized Exchange Latency Test v5.3.2
# Size       Avg Latency(us)   Min Latency(us)   Max Latency(us)  Iterations
2                   17615.87          11288.89          21322.09        1000
4                   16070.89           3002.21          21451.92        1000
8                   15235.21           5139.31          18867.68        1000
16                  14830.46           6513.51          17138.22        1000
32                  15844.06           5912.86          19503.95        1000
64                  14952.21           2665.28          22500.39        1000
128                   617.54            508.83            662.27        1000

====================================================================
===================== MPICH+32procs/node+10nodes =======================
# OSU MPI All-to-All Personalized Exchange Latency Test v5.3.2
# Size       Avg Latency(us)   Min Latency(us)   Max Latency(us)  Iterations
2                      88.55             82.38             93.58        1000
4                      90.62             83.07             96.60        1000
8                      96.14             86.76            103.09        1000
16                    111.50             98.27            119.58        1000
32                    155.38            125.18            169.13        1000
64                    238.63            193.72            253.32        1000
128                   480.29            368.26            528.42        1000

====================================================================
```

**Comment by jayeshkrishna** [comment] 2017-02-07 22:18
The above test was run on
* 10 dual-socket Intel Xeon Broadwell nodes (E5-2697V4, 2.3 GHz, 18-core)
* 360 MPI procs (36 cores/36 procs per node) vs 320 MPI procs (32 procs/node)
* FDR InfiniBand fabric interface (Mellanox Technologies MT27600 [Connect-IB])

**Comment by jayeshkrishna** [comment] 2017-03-06 18:25
Do you have any approx time estimate on when these parameters will be retuned ?

**Comment by raffenet** [comment] 2017-07-28 19:10
@jayeshkrishna I think you had mentioned to me in passing that you may have found the source of this issue. Was that the case?

**Comment by Bayyapu** [comment] 2017-08-31 16:07
The above issue occurs with ch4-UCX on ACME queue on Blues. Adding bind-to core option resolves the performance issue. This option avoids over subscription of the resources in ch4-ucx with the progressive threads.

**Comment by hzhou** [comment] 2021-03-13 20:00
Seems the issue is resolved by adding "bind-to" option. Thus I am closing this issue.

**Closed by hzhou** 2021-03-13 20:00 UTC
