### ISSUE TITLE
bugs/jenkins: ch4:ucx sporadic `proxy_ep` assertion failure 

### ISSUE THREAD

**Issue by Bayyapu** [pmodels/mpich#3537] opened 2019-01-28 16:32 UTC
There is a failure at assertion  'proxy_ep->uct_ep != ((void *)0)'  in ch4:ucx. 

Failure example: 
https://jenkins.mpich.org/job/mpich-review-ch4-ucx/1700/compiler=gnu,jenkins_configure=no-inline,label=ib64/testReport/junit/(root)/summary_junit_xml/44_____coll_alltoallv_10__/

Note: The error occurs very rarely, so one might need to run the test tens of times for it to show up

**Comment by hzhou** [comment] 2019-05-13 14:47
This error constantly shows up in our Jenkins tests, but not quite reproducible. There is an `xfail` -- PR #3618 -- related to it. However, the error shows up in multiple tests sporadically. The candidates include:

    coll/allgather2 10 gentran_ring
    coll/redscatblk3 8 gentran_recexch
    coll/alltoallv 8 gentran_scattered
    coll/allgather3 10 gentran_brucks
    coll/alltoallv 10
    coll/alltoallv0 10
    coll/red_scat_block2 10
    comm/ic2 33
    threads/pt2pt/multisend4 5

It happens to various builds (debug, am_only, strict), however, for the last 20 builds or so, I haven't seen it with external build.

**Comment by hzhou** [comment] 2019-05-13 15:19
Here is a related UCX issue: https://github.com/openucx/ucx/issues/3555

**Comment by hzhou** [comment] 2019-05-13 16:20
Running manual tests in shell script for hundreds of times, I am yet to be able to reproduce the error :(

**Comment by hzhou** [comment] 2019-05-13 21:12
This is what I understand so far (feel free to correct me): 

At init, ucx will create endpoint configured with all available uct channels. On first successful communication, that endpoint (`ucp_proxy_ep`) will narrow down to the specific successful `uct_ep` by setting its `uct_ep` to `NULL` (originally was to `super` or self). It appears on race condition, multiple thread may try to do that (calling `ucp_proxy_ep_replace`), then one of them will trigger the assertion error.

**Comment by hzhou** [comment] 2019-05-16 12:12
It is part of the ucp `wireup`, or connection, process. 

The connection should be made during the first `MPI_Barrier` call, but somehow, the ep is still not fully swapped during the first `MPI_Isend`, causing the error. -- still not sure how it happens nor the detailed process.

I cannot reproduce this on the new Jenkins server.

**Comment by raffenet** [comment] 2019-05-16 13:44
It could be a bug in one of the dependent libraries in that case. Old jenkins nodes are pretty far behind when it comes to rdma support.

**Comment by hzhou** [comment] 2020-06-21 00:16
Haven't seen this bug since we moved to new Jenkins server. I think @raffenet probably was correct that this is to do with old libraries. Closing this issue.

**Closed by hzhou** 2020-06-21 00:16 UTC
