### ISSUE TITLE
build: ch4-ucx on aarch64

### ISSUE THREAD

**Issue by jeffhammond** [pmodels/mpich#5111] opened 2021-03-07 01:43 UTC
# Error
```
make[5]: Entering directory '/samsung/MPICH/mpich-3.4.1/build/modules/ucx/src/ucm'
source='bistro/bistro_aarch64.c' object='bistro/libucm_la-bistro_aarch64.lo' libtool=yes \
DEPDIR=.deps depmode=pgcc /bin/bash ../../../../../modules/ucx/depcomp \
/bin/bash ../../libtool  --tag=CC   --mode=compile nvc -DHAVE_CONFIG_H -I. -I../../../../../modules/ucx/src/ucm -I../..  -DCPU_FLAGS="" -I/samsung/MPICH/mpich-3.4.1/build/modules/ucx/../../../modules/ucx/src -I/samsung/MPICH/mpich-3.4.1/build/modules/ucx -I/samsung/MPICH/mpich-3.4.1/build/modules/ucx/src -DUCM_MALLOC_PREFIX=ucm_dl -fno-strict-aliasing -DUSE_LOCKS=1 -DMALLINFO_FIELD_TYPE=int  -O3 -g -Wall -Werror --display_error_number --diag_suppress 181 --diag_suppress 1215 --diag_suppress 1901 -Wno-long-long -Wno-deprecated-declarations -Wnested-externs -Wshadow -Wno-deprecated-declarations  -c -o bistro/libucm_la-bistro_aarch64.lo `test -f 'bistro/bistro_aarch64.c' || echo '../../../../../modules/ucx/src/ucm/'`bistro/bistro_aarch64.c
libtool: compile:  nvc -DHAVE_CONFIG_H -I. -I../../../../../modules/ucx/src/ucm -I../.. -DCPU_FLAGS= -I/samsung/MPICH/mpich-3.4.1/build/modules/ucx/../../../modules/ucx/src -I/samsung/MPICH/mpich-3.4.1/build/modules/ucx -I/samsung/MPICH/mpich-3.4.1/build/modules/ucx/src -DUCM_MALLOC_PREFIX=ucm_dl -fno-strict-aliasing -DUSE_LOCKS=1 -DMALLINFO_FIELD_TYPE=int -O3 -g -Wall -Werror --display_error_number --diag_suppress 181 --diag_suppress 1215 --diag_suppress 1901 -Wno-long-long -Wno-deprecated-declarations -Wnested-externs -Wshadow -Wno-deprecated-declarations -c ../../../../../modules/ucx/src/ucm/bistro/bistro_aarch64.c -MD  -fPIC -DPIC -o bistro/.libs/libucm_la-bistro_aarch64.o
"../../../../../modules/ucx/src/ucm/bistro/bistro_aarch64.c", line 69: error #68: integer conversion resulted in a change of sign
          .reg3 = MOVZ(R15, 3, (uintptr_t)hook >> 48),
                  ^

"../../../../../modules/ucx/src/ucm/bistro/bistro_aarch64.c", line 70: error #68: integer conversion resulted in a change of sign
          .reg2 = MOVK(R15, 2, (uintptr_t)hook >> 32),
                  ^

"../../../../../modules/ucx/src/ucm/bistro/bistro_aarch64.c", line 71: error #68: integer conversion resulted in a change of sign
          .reg1 = MOVK(R15, 1, (uintptr_t)hook >> 16),
                  ^

"../../../../../modules/ucx/src/ucm/bistro/bistro_aarch64.c", line 72: error #68: integer conversion resulted in a change of sign
          .reg0 = MOVK(R15, 0, (uintptr_t)hook),
                  ^

"../../../../../modules/ucx/src/ucm/bistro/bistro_aarch64.c", line 73: error #68: integer conversion resulted in a change of sign
          .br   = BR(R15)
                  ^

5 errors detected in the compilation of "../../../../../modules/ucx/src/ucm/bistro/bistro_aarch64.c".
Makefile:823: recipe for target 'bistro/libucm_la-bistro_aarch64.lo' failed
make[5]: *** [bistro/libucm_la-bistro_aarch64.lo] Error 1
```

# Reproduce
```
wget http://www.mpich.org/static/downloads/3.4.1/mpich-3.4.1.tar.gz
tar -xaf mpich-3.4.1.tar.gz
cd mpich-3.4.1
mkdir build
cd build
../configure FC=nvfortran CC=nvc CXX=nvc++ --with-device=ch4:ucx
```

**Comment by tomgao56** [comment] 2021-09-03 09:46
I have met the same problem.

**Comment by raffenet** [comment] 2021-09-08 20:04
I don't have access to aarch64 hardware at the moment, but I can confirm the bug using a multiarch docker container on my laptop. I'll submit an issue to the UCX repo.

**Comment by raffenet** [comment] 2022-08-30 18:17
Going to close this as wontfix since the issue is upstream (https://github.com/openucx/ucx/issues/6576). We recommend using an external UCX when building MPICH with NVHPC compilers.

**Closed by raffenet** 2022-08-30 18:17 UTC
