### ISSUE TITLE
build: configure problem of mpich

### ISSUE THREAD

**Issue by pistachio-xin** [pmodels/mpich#6205] opened 2022-10-09 12:18 UTC
hi, everyone,
I met a problem when I run the code './configure --prefix=/home/user/mpich4/mpich_install 2>&1 | tee c.txt' in the process of installing mpic, there have the following error:
configure: error: working directory cannot be determined.
So, if somebody can help me to solve this problem, I will be thanks very much.

**Comment by hzhou** [comment] 2022-10-09 13:26
@pistachio-xin Could you upload `c.txt`? We'll need more context to troubleshoot.

**Comment by pistachio-xin** [comment] 2022-10-09 13:31
> @pistachio-xin Could you upload `c.txt`? We'll need more context to troubleshoot.
@hzhou 
[c.txt](https://github.com/pmodels/mpich/files/9741658/c.txt)
yes, but there just have one error: "configure: error: working directory cannot be determined."

**Comment by hzhou** [comment] 2022-10-09 13:41
What do you get when you type `pwd` at the command prompt?

**Comment by pistachio-xin** [comment] 2022-10-09 13:45
@hzhou 
![批注 2022-10-09 214501](https://user-images.githubusercontent.com/81011698/194760344-0fa2c268-33f7-48dc-a0db-21d08582f640.jpg)
Can you see this picture?

**Comment by hzhou** [comment] 2022-10-09 13:47
Yes. That looks all right.

**Comment by hzhou** [comment] 2022-10-09 13:53
Okay, try this then --
```
ac_pwd=`pwd` && test -n "$ac_pwd" &&
ac_ls_di=`ls -di .` &&
ac_pwd_ls_di=`cd "$ac_pwd" && ls -di .` ||
  echo "working directory cannot be determined"
```

This is what in the `configure` script that produced the error. See if you can reproduce it.

**Comment by pistachio-xin** [comment] 2022-10-09 13:57
@hzhou 
![11](https://user-images.githubusercontent.com/81011698/194760930-c8c6e5bc-f629-4371-ba92-e31218eae9c0.jpg)
Is it right?

**Comment by hzhou** [comment] 2022-10-09 13:59
Good, you reproduced the error. Now manually try one command at a time and try to figure out which step failed.

**Comment by pistachio-xin** [comment] 2022-10-09 14:05
@hzhou Very sorry that I have not understood the method. Which command I need to try?

**Comment by hzhou** [comment] 2022-10-09 14:10
I'll be busy for a while. Meanwhile, please try some online shell scripting resources until you fully understand the command you just tried. I'll help you later if you still couldn't figure it out.

**Comment by pistachio-xin** [comment] 2022-10-09 14:13
@hzhou Ok, thanks for your help! I will try to understand those command.

**Comment by hzhou** [comment] 2022-10-09 18:21
@pistachio-xin Here is a list of commands you can try:
```
ac_pwd=`pwd` && echo $ac_pwd

ac_pwd=`pwd` && test -n "$ac_pwd" && echo $ac_pwd

ac_pwd=`pwd` && test -n "$ac_pwd" && ac_ls_di=`ls -di .` && echo $ac_ls_di

ac_pwd=`pwd` && test -n "$ac_pwd" && ac_ls_di=`ls -di .` && ac_pwd_ls_di=`cd "$ac_pwd" && ls -di .`  && echo $ac_pwd_ls_di
```

I suspect it is `cd $ac_pwd` has issue, so also try `cd /home/user/mpich4/mpich-4.0.1`

**Comment by pistachio-xin** [comment] 2022-10-10 01:45
@hzhou I think maybe you want to verify that the pwd directory is the current directory. If yes, the directory id must be the same, but it seems like doesn't has issue.
![22](https://user-images.githubusercontent.com/81011698/194789551-e0614695-e26c-4529-8ebd-46c766cf2ffb.jpg)

**Comment by hzhou** [comment] 2022-10-10 01:53
Looks like 
```
ac_ls_di=`ls -di .`
```
returned non-zero. And why `cd ` prints the directory listing? Did you had `ls` and `cd` aliased into something?

**Comment by pistachio-xin** [comment] 2022-10-10 02:05
@hzhou Nope, I have checked the .bashrc file, there didn't aliased ls and cd.  
![44](https://user-images.githubusercontent.com/81011698/194790554-58810527-e31c-4dea-9970-d32337840e47.jpg)

**Comment by hzhou** [comment] 2022-10-10 02:35
Try 
```
ls -di .
echo $?
```

**Comment by pistachio-xin** [comment] 2022-10-10 02:44
@hzhou 
![5](https://user-images.githubusercontent.com/81011698/194792739-d85b7b04-b465-4307-ab89-720a3b1c1f38.jpg)

**Comment by hzhou** [comment] 2022-10-10 03:20
The error code of 255 is the issue. What is your system and could you upload the man page of your `ls`?

**Comment by pistachio-xin** [comment] 2022-10-10 03:33
@hzhou My system is Centos7, and the man page of ls is showing in the following file.
[output.txt](https://github.com/pmodels/mpich/files/9743237/output.txt)

**Comment by hzhou** [comment] 2022-10-10 04:15
Does your `ls` always return 255? Try -
```
ls
echo $?
```

**Comment by hzhou** [comment] 2022-10-10 04:17
I am not sure what's going on with `ls` on your system. You may try hack the `configure` script. Just edit and search for the error message and remove the error checking.

**Comment by pistachio-xin** [comment] 2022-10-10 04:47
@hzhou 

> Does your `ls` always return 255? Try -
> 
> ```
> ls
> echo $?
> ```

Yes, and in the another pc, there are also 255, but that pc doesn't have the problem of configure.


> I am not sure what's going on with `ls` on your system. You may try hack the `configure` script. Just edit and search for the error message and remove the error checking.

Ok, thank you very very much, I will try to check the configure script.

**Comment by hzhou** [comment] 2022-10-12 03:08
I am closing this issue since it is not related to MPICH. @pistachio-xin  If you still need help, feel free to reopen it.

**Closed by hzhou** 2022-10-12 03:08 UTC
