### ISSUE TITLE
MPICH 4.1 has man files with clashing names on case insensitive file systems

### ISSUE THREAD

**Issue by giordano** [pmodels/mpich#6431] opened 2023-03-05 17:50 UTC
For example
```console
% curl -Lfs https://github.com/JuliaBinaryWrappers/MPICH_jll.jl/releases/download/MPICH-v4.1.0%2B0/MPICH.v4.1.0.aarch64-apple-darwin-libgfortran5-mpi+mpich.tar.gz | tar tzf - | grep -Ei 'MPI_(Aint|Count|Offset).3' 
share/man/man3/MPI_AINT.3
share/man/man3/MPI_Aint.3
share/man/man3/MPI_COUNT.3
share/man/man3/MPI_Count.3
share/man/man3/MPI_OFFSET.3
share/man/man3/MPI_Offset.3
```
It'd be nice not to have these clashes in the first place.  I believe also some docs files used to have these problems, I don't know if that has been solved, but the solution for us has been to stopped shipping these files altogether.

**Comment by giordano** [comment] 2023-03-05 18:30
You can see that also the MPICH 4.1 build in Debian experimental has the same duplicate files: https://packages.debian.org/experimental/all/mpich-doc/filelist

**Comment by hzhou** [comment] 2023-03-06 17:25
`MPI_AINT` and `MPI_Aint` are two different entries. The former is a builtin datatype constant. The latter is a `typedef` C type. They both points to `mpiconsts` man page though. What happens on case insensitive file systems? If it is just one file overriding another during installation, then that should be fine.

**Comment by giordano** [comment] 2023-03-06 17:35
> What happens on case insensitive file systems? If it is just one file overriding another during installation, then that should be fine.

We use the git tree hash of the tarball to verify integrity of the unpacked archive, but if some files are missing depending on the file system, then the check fails.

**Comment by hzhou** [comment] 2023-03-06 17:52
I am marking this issue as `wontfix`. Both `MPI_AINT` and `MPI_Aint` entries are nice to keep for case sensitive filesystems -- I belive it is the common case. Otherwise, either `man MPI_AINT` or `man MPI_Aint` will be missing. The issue is particular to downstream's CI process. We suggest to adopt downstream-specific solutions.

**Comment by hzhou** [comment] 2023-03-10 22:33
Close as wontfix

**Closed by hzhou** 2023-03-10 22:33 UTC
Labels: wontfix
