### ISSUE TITLE
coll: temporary buffers in collectives

### ISSUE THREAD

**Issue by raffenet** [pmodels/mpich#3468] opened 2018-12-13 22:38 UTC
There are many instances of collectives using temporary buffers in which potentially non-contiguous user-supplied datatypes are used. This requires allocating more memory than there is useful data, complex offset manipulation using extents, and redundant datatype processing during communication. Ideally temporary buffers would only work with contig data to minimize these drawbacks. See #3466 for an example.

**Comment by hzhou** [comment] 2019-01-21 21:00
@raffenet I think we should do a survey of current codebase and list the scope here.

**Comment by hzhou** [comment] 2019-01-22 23:18
To reproduce the bug:
```
#include <stdio.h>
#include <mpi.h>

int NP = 2;

int mpi_size;
int mpi_id;
float pf_send[4];
float pf_recv[4*16];int main(int argc, char** argv)
{
    MPI_Init(NULL, NULL);
    MPI_Comm_size(MPI_COMM_WORLD, &mpi_size);
    MPI_Comm_rank(MPI_COMM_WORLD, &mpi_id);
    for (int  i = 0; i<4; i++) {
        pf_send[i] = (mpi_id / 2 * 2 + i / 2) * 4 + (mpi_id % 2 * 2 + i % 2) + 1;
    }
    printf("%d: %2.0f %2.0f %2.0f %2.0f\n", mpi_id, pf_send[0], pf_send[1], pf_send[2], pf_send[3]);
    MPI_Datatype type_A;
    MPI_Datatype type_B;
    MPI_Type_vector(2, 2, 4, MPI_FLOAT, &type_A);
    MPI_Type_create_resized(type_A, 0, 16 / NP * 4, &type_B);
    MPI_Type_commit(&type_B);
    int pn_counts[4] = {1,1,1,1};
    int pn_displs[4] = {0,1,2,3};
    for (int  i = 0; i<4; i++) {
        pn_displs[i] *= NP;
    }
    MPI_Allgatherv(pf_send, 4, MPI_FLOAT, pf_recv, pn_counts, pn_displs, type_B, MPI_COMM_WORLD);
    if (mpi_id == 0) {
        puts("----------------------------");
        for (int  i = 0; i<16; i++) {
            printf("%2.0f %2.0f %2.0f %2.0f\n", pf_recv[i*4], pf_recv[i*4+1], pf_recv[i*4+2], pf_recv[i*4+3]);
        }
    }
    MPI_Finalize();
    return 0;
}
```

**Comment by hzhou** [comment] 2019-01-22 23:21
`mpicc test.c && mpirun -n 4 ./a.out` 

Set `NP=2` or `1` produces the correct result. Set `NP` to `4` or `8` or `16` reproduces the error output.

**Comment by hzhou** [comment] 2019-01-23 16:38
`MPIR_Datatype_get_size_macro(datatype, size)` returns the `size` member, which always sets to the aggregated total size of the data inside the datatype, therefore using `MPI_BYTE` with `size` count wlll  work regardless upper bound or lower bound. I guess the question is whether `MPIR_Localcopy` can map any datatype at `count >= 1` reliably from and to `MPI_BYTE` at `count * size`.

**Comment by Bayyapu** [comment] 2019-03-22 19:40
@hzhou  I am trying to note the FY19Q2 progress.  Could you please let me know the update or point me to the correct PR that i need to see for the progress for this issue?

**Comment by hzhou** [comment] 2019-03-25 14:50
@Bayyapu Since Pavan is making a refactor on datatype code, this issue is best to wait until that refactor is merged in first. Please remove the Q2 milestone or move it to FY19Q3.

**Comment by pavanbalaji** [comment] 2019-03-25 14:52
The datatype refactor code shouldn't affect this.  A bunch of the refactoring commits are already in and very little at the MPI-layer would need refactoring updates.

**Comment by hzhou** [comment] 2019-03-25 15:23
@pavanbalaji Alright, but I need your input on this. One way to interpret this issue is that the test case is questionable. Per standard, the intention of `extent` is to mark where to put the next data item. In the test case, the resized extent is smaller than the upper bound, therefore, packing data according to the resized extent will result in data corruption. However, in this case, the packing of multiple data is due to internal algorithm, it does not clear to the user why the corruption arises as interface of `allgatherv` has manually set displacements explicitly.

The fix essentially does packing/unpacking of the derived data internally. While it meets the user expected results, it also sets the example that implementation internally cannot interpret the `extent` as where to pack data -- potentially limit opportunities of optimizations. 

Either way, I also need your input on whether we should just to this patch locally -- only to `Allgatherv` or apply similar patches to all other collectives (other than reductions maybe).

**Comment by pavanbalaji** [comment] 2019-03-25 15:33
The issue seems to indicate that the buffer allocation is large.  But you are indicating data corruption.  Is this data corruption in the patch that @raffenet created or in the current `mpich/master`?

**Comment by hzhou** [comment] 2019-03-25 15:35
The data corruption is in the master.

**Comment by hzhou** [comment] 2019-03-25 15:36
It is not about buffer too large or too small. It is because `Allgatherv` internally sends multiple data items and when they are packed according to user specified `extent`, it corrupts the data.

**Comment by pavanbalaji** [comment] 2019-03-25 15:37
I think this issue deals with a different problem.  If there's data corruption, that's a separate issue.

**Comment by hzhou** [comment] 2019-03-25 15:38
> I think this issue deals with a different problem. If there's data corruption, that's a separate issue.

What do you mean? The issue is about data corruption.

**Comment by pavanbalaji** [comment] 2019-03-25 15:41
The issue description only talks about "too much memory being allocated":

> There are many instances of collectives using temporary buffers in which potentially non-contiguous user-supplied datatypes are used. This requires allocating more memory than there is useful data, complex offset manipulation using extents, and redundant datatype processing during communication. Ideally temporary buffers would only work with contig data to minimize these drawbacks. See #3466 for an example.

**Comment by hzhou** [comment] 2019-03-28 14:25
After discussion with Pavan, the original test case was determined to be a wrong usage. When user set a extent with `MPI_Type_create_resized` to a smaller value than the datatype's true upper bound, the resulting data corruption is not an error per standard. The `extent` of a datatype marks the stride where consecutive data is to be placed. Multiple data packing could happen internally -- as in this case of `allgather` algorithm.

However, using packed `tmp_buf` is a good idea. When the data arrives from the wire they are always packed anyway and using derived datatype in `tmp_buf` only incurs overhead (and more convoluted code). Therefore, we will apply this patch to all collective algorithm (other than where operation is needed such as `allreduce`) whenever tmp_buf is being used. Note that this patch is not a sanction of the erroneous usage of `MPI_Type_create_resized` in the original bug report.

**Comment by pavanbalaji** [comment] 2019-03-28 14:31
To be clear, I did not see the user code, so I don't know if it's incorrect.  I just saw what @hzhou showed to me on the white paper and that looked incorrect.  😃 

Reduced extent is not always incorrect.  There are cases where they make sense.  In the example that Hui showed, it was incorrect.  Also, the example that was showed had nothing to do with the `tmp_buf`, so I don't fully understand the correlation.

**Comment by pavanbalaji** [comment] 2019-03-28 14:33
Specifically, this code is incorrect: https://github.com/pmodels/mpich/issues/3468#issuecomment-456602060

**Comment by hzhou** [comment] 2019-03-28 14:37
The bug case was the original background that @raffenet did the `tmp_buf` patch and the opening of this issue, although the title and description of this issue do not link to that background -- and rightly so.

**Comment by hzhou** [comment] 2019-03-29 17:57
Pushed commits on to PR# 3466, ready for review and merge. Closing this issue.

**Closed by hzhou** 2019-03-29 17:57 UTC
