### ISSUE TITLE
Slurm jobs fail for hostnames that do NOT end with a number

### ISSUE THREAD

**Issue by mrmhodak** [pmodels/mpich#3946] opened 2019-07-25 22:48 UTC
Hostname parsing fails for nodes that do not end with a number, for example running on a node named "n", the following error is reported 

> [hpcuser@n ~]$ srun -n 6 -N 1 --pty /bin/bash
> [hpcuser@n ~]$ prun ./a.out
> [prun] Master compute host = n
> [prun] Resource manager = slurm
> [prun] Launch cmd = mpiexec.hydra -bootstrap slurm ./a.out (family=mpich)
> Error: node list format not recognized. Try using '-hosts=<hostnames>'.
> /opt/ohpc/pub/utils/prun/1.3/prun: line 102:  2528 Aborted                 (core dumped) $cmd

Changing hostname to "n1" (and changing slurm config as appropriate) the same job runs as expected. 
This on with 3.3 on OpenHPC 1.3.8, which has the latest slurm_query_node_list.c backported from 3.3.1

**Comment by gcongiu** [comment] 2019-07-26 14:50
@mrmhodak can you try #3947 and see if it solves your issue?

**Comment by mrmhodak** [comment] 2019-07-31 17:15
I need help with verifying. In my tests, it seems that slurm_query_node_list.c is not used at all - that is if I add a print statement there is no output. 

This is with fresh git checkout, master branch, executing as "mpiexec.hydra -bootstrap slurm ./a.out"
What am I missing? 

Configure flags (I only use --prefix)?

**Comment by gcongiu** [comment] 2019-08-01 00:56
I think `-launcher` is what you are looking for:
```
mpiexec --help
...
Hydra specific options (treated as global):

  Launch options:
    -launcher                        launcher to use (ssh rsh fork slurm ll lsf sge manual persist)
    -launcher-exec                   executable to use to launch processes
    -enable-x/-disable-x             enable or disable X forwarding
...
```

**Comment by mrmhodak** [comment] 2019-08-01 22:02
This works and fixes the issue for me with OpenHPC 3.3 version (it has #3572 patch).

However, when using latest GitHub code, there is still a failure when the node name does not end with number.

**Comment by gcongiu** [comment] 2019-08-01 22:05
@mrmhodak if you mean master branch then yes. This patch has not been merged into master yet.

> However, when using latest GitHub code, there is still a failure when the node name does not end with number.

**Comment by mrmhodak** [comment] 2019-08-01 22:07
I mean main branch with your patch included

**Comment by gcongiu** [comment] 2019-08-01 22:19
@mrmhodak I am sorry but I am confused. You reported a problem that was showing up with master, which includes the patch #3578 (#3572 is the corresponding issue that was fixed by such patch). Now you are saying #3572 (I assume you mean #3578) fixes your issue? Your original report, following referenced, clearly shows that you were using the code in patch #3578. Can you clarify? 

> Hostname parsing fails for nodes that do not end with a number, for example running on a node named "n", the following error is reported
> 
> > [hpcuser@n ~]$ srun -n 6 -N 1 --pty /bin/bash
> > [hpcuser@n ~]$ prun ./a.out
> > [prun] Master compute host = n
> > [prun] Resource manager = slurm
> > [prun] Launch cmd = mpiexec.hydra -bootstrap slurm ./a.out (family=mpich)
> > Error: node list format not recognized. Try using '-hosts='.
> > /opt/ohpc/pub/utils/prun/1.3/prun: line 102:  2528 Aborted                 (core dumped) $cmd
> 
> Changing hostname to "n1" (and changing slurm config as appropriate) the same job runs as expected.
> This on with 3.3 on OpenHPC 1.3.8, which has the latest slurm_query_node_list.c backported from 3.3.1

**Comment by mrmhodak** [comment] 2019-08-01 22:47
I found the problem on 3.3 with a #3578 patch. This is built by  openhpc/ohpc and uses 2 more patches  - minor ones applying to configuration mostly. For this build, when I add the patch and rebuild from OpenHPC srpm the resulting package works.

In addition, I have also tried to test with latest master and that is where I am running into issues. The fix  does not seem to work there. To give you more details: At first, I could not get the code where the patch is to execute at all - the slurm libraries get detected and the `#if defined(HAVE_LIBSLURM)` condition is satisfied meaning that the part of the code where the patch is is not even compiled. So, I force it by making the conditional false - it is a hack, of course, but I figured it may be OK to test this function. And under these conditions I see that patch fail - and if I modify SLURM_NODELIST variable to have a number at the the function is executed.

Hope this make sense now.

**Comment by mrmhodak** [comment] 2019-08-01 22:56
@gcongiu: Re-reading your comment I see where the confusion is: What works is adding #3947 to OpenHPC build of 3.3 which already had #3578.

What does not work is the current master with #3947.

**Comment by gcongiu** [comment] 2019-08-01 23:40
@mrmhodak this is not possible because I have just realized that the "fix" in #3947 is practically equivalent to #3578 from the point of view of your use case. If #3578 does works so should #3947. #3578 already introduced support for alphabetic-only node names. The new patch only ignores node names that start with a number or contain only numbers. This means the problem is somewhere else.

Can you use a clean version of current mpich master and attach your `config.log`? Can you also print the environment `SLURM_NODELIST`?

**Comment by mrmhodak** [comment] 2019-08-01 23:52
@gcongiu: With clean master the part of the code where your patch applies is not even compiled - ./configure enables slurm and I do not see any way to disable. Does this still make sense to try?  

BTW, MPI jobs work in such a case. It looks like OpenHPC rpm build disables slurm, I cannot reproduce this in my building environment. 

As for SLURM_NODELIST:
 

> [test@hpctestx ~]$ echo $SLURM_NODELIST
> hpctestx

**Comment by gcongiu** [comment] 2019-08-02 02:05
@mrmhodak I have replicated your problem. The proposed patch does not fix it.

**Comment by mrmhodak** [comment] 2019-08-02 02:20
That makes sense, I will wait for the patch

**Comment by gcongiu** [comment] 2019-08-02 15:12
@mrmhodak I have updated #3947 if you want to give it a try. I have tested it and it seems to work for me.

**Comment by mrmhodak** [comment] 2019-08-05 05:25
I can confirm that #3947 works for me as well.

**Comment by mrmhodak** [comment] 2019-08-16 05:18
So, the issue is still not fixed. It still fails when the nodename contains underscore. Example, works with hostname "licomaster", but changing to "lico_master" causes failure:

[hpcuser@licomaster ~]$ export SLURM_NODELIST=lico_master
[hpcuser@licomaster ~]$ prun ./a.out
[prun] Master compute host = licomaster
[prun] Resource manager = slurm
[prun] Launch cmd = mpiexec.hydra -bootstrap slurm ./a.out (family=mpich)
Error: node list format not recognized. Try using '-hosts=<hostnames>'.
/opt/ohpc/pub/utils/prun/1.3/prun: line 102:  9076 Aborted                 (core dumped) $cmd

**Comment by gcongiu** [comment] 2019-08-16 14:07
From https://tools.ietf.org/html/rfc952:

ASSUMPTIONS

   1. A "name" (Net, Host, Gateway, or Domain name) is a text string up
   to 24 characters drawn from the alphabet (A-Z), digits (0-9), minus
   sign (-), and period (.).  Note that periods are only allowed when
   they serve to delimit components of "domain style names". (See
   RFC-921, "Domain Name System Implementation Schedule", for
   background).  No blank or space characters are permitted as part of a
   name. No distinction is made between upper and lower case.  The first
   character must be an alpha character.  The last character must not be
   a minus sign or period.  A host which serves as a GATEWAY should have
   "-GATEWAY" or "-GW" as part of its name.  Hosts which do not serve as
   Internet gateways should not use "-GATEWAY" and "-GW" as part of
   their names. A host which is a TAC should have "-TAC" as the last
   part of its host name, if it is a DoD host.  Single character names
   or nicknames are not allowed.

According to the RFC hostnames are not supposed to have `_` or `+` or any other character rather than `-` and `.`. If your hostname are using such naming convention I think that is an error. I will fix the patch to include `.`.

**Comment by mrmhodak** [comment] 2019-08-16 14:13
Thanks for this, was not aware of that.

**Closed** 2019-10-15 16:10 UTC
