### ISSUE TITLE
build/jenkins: PGI c++ compilers not functioning correctly

### ISSUE THREAD

**Issue by pavanbalaji** [pmodels/mpich#3503] opened 2019-01-17 00:18 UTC
The PGI C++ compilers seem to fail to build programs.  Jenkins tests fail with the following configure error:

```
checking whether the C++ compiler pgc++ can build an executable... no
configure: error: Aborting because C++ compiler does not work.  If you do not need a C++ compiler, configure with --disable-cxx
```

Jenkins link: https://jenkins.mpich.org/job/mpich-master-ch3-ubuntu/

**Comment by raffenet** [comment] 2019-01-17 15:47
This happened when I updated the Jenkins configuration to use `pgc++` instead of `pgcpp` for C++. `pgcpp` is no longer provided by PGI. Our Jenkins uses a very old installation from 2013. My hope is the version installed on the new Jenkins will just work (once we get the license issue fixed). If that is the case, I propose dropping the existing PGI Jenkins configurations.

**Comment by pavanbalaji** [comment] 2019-01-17 15:49
Why are you proposing to drop the PGI configurations if they are expected to work on the new servers?

**Comment by raffenet** [comment] 2019-01-17 15:50
Drop them only on the existing Jenkins server. New one will retain them.

**Comment by pavanbalaji** [comment] 2019-01-17 15:52
I thought the jenkins frontend is going to stay the same.  Only the backend servers are changing.  If the backend servers are being upgraded relatively soon, it seems like a hassle to disable it now and remember to enable them again.

**Comment by pavanbalaji** [comment] 2019-01-17 15:55
How will the port take place?  Will the configurations simply be copied out?  If yes, someone will need to remember to re-enable them.

**Comment by raffenet** [comment] 2019-01-17 15:56
Yes, configurations are being copied and tested as we go.

**Comment by raffenet** [comment] 2019-01-17 16:01
To me, it doesn't matter if we drop the configs or just ignore them (as long as the new version works as expected).

**Comment by pavanbalaji** [comment] 2019-01-17 16:02
I guess it depends on what length of time we are thinking of.  If it's a week or two, it's better to ignore it (but let it fail).

**Comment by naromero77** [comment] 2019-09-25 04:11
@raffenet This may be too off topic. Does MPICH build with a recent version of `pgc++`? I was trying to do build MPICH 3.3.1 via Spack using PGI 19.7. But ran into this link time error:
```
     9743      GEN      lib/libmpi.la
     9744      CXXLD    lib/libmpicxx.la
     9745      CCLD     src/env/mpichversion
     9746      CCLD     src/env/mpivars
     9747      GEN      lib/libmpifort.la
     9748    pgc++-Error-Unknown switch: -pthread
  >> 9749    make[2]: *** [lib/libmpicxx.la] Error 1
     9750    make[2]: *** Waiting for unfinished jobs....
     9751    make[2]: Leaving directory `/sandbox/naromero/tmp/spack-stage/mpich-3.3.1-6pu2tu4hr4rqvsjt3hnq7kv7nrv4kfrc/spack-src'
  >> 9752    make[1]: *** [all-recursive] Error 1
     9753    make[1]: Leaving directory `/sandbox/naromero/tmp/spack-stage/mpich-3.3.1-6pu2tu4hr4rqvsjt3hnq7kv7nrv4kfrc/spack-src'
```

I am not sure if the problem is Spack, MPICH build system, or libtool.

**Comment by raffenet** [comment] 2019-09-25 13:40
@naromero77 I don't think `-pthread` is coming from our build system. MPICH *builds* with PGI compilers in our nightly testing right now, but has problems at runtime that we need to investigate.

**Comment by raffenet** [comment] 2019-09-25 13:43
Hmm, now that I think some more, it's possible it is coming from a submodule.

**Comment by raffenet** [comment] 2019-09-25 15:02
@naromero77 what is your complete `spack` invocation? FWIW, I run into an issue when building a dependency (`pkgconf`) with PGI compilers and never reach the MPICH build stage.

**Comment by naromero77** [comment] 2019-09-25 16:13
This looks like a PGI compiler configuration issue. I was able to work around the problem by modifying the localrc file for the PGI compiler. The issue is not specific to MPICH and happens to other packages too.

Just for future reference. If I find issue with the Spack MPICH package, would you prefer that I create a GitHub issue at the Spack repo or the MPICH repo?

**Comment by raffenet** [comment] 2019-09-25 17:40
I think Spack repo and tag me in the description.

**Comment by hzhou** [comment] 2021-09-10 04:46
This issue is for old system and I believe it is outdated. I am closing this for now. If there is still issue regarding pgi compilers (must be, that is full of issues), open a new issue with specific descriptions.

**Closed by hzhou** 2021-09-10 04:46 UTC
