### ISSUE TITLE
bug in indexed types

### ISSUE THREAD

**Issue by roblatham00** [pmodels/mpich#3846] opened 2019-06-11 17:58 UTC
As seen on discuss list:
https://lists.mpich.org/pipermail/discuss/2019-June/011200.html

On on any good MPI version, the output of the attached example is:

Rank 1: Element # 33 : {40,106,105,204,208,200},8
Rank 1: Element # 34 : {61,105,106,201,208,205},8
Rank 1: Element # 35 : {40,105,107,200,212,209},8
Rank 1: Element # 36 : {62,107,105,210,212,202},8
Rank 1: Element # 37 : {40,108,106,213,216,204},8
Rank 1: Element # 38 : {42,110,85,223,227,108},8

On the mpich/master branch, since may 24,
commit 60035bb7b9766db15041033959e4209f0ad936b,
  the output is:

Rank 1: Element # 33 : {40,106,105,204,208,200},8
Rank 1: Element # 34 : {52,76,104,74,197,195},8
Rank 1: Element # 35 : {62,105,65,202,203,40},8
Rank 1: Element # 36 : {63,66,106,41,207,206},8
Rank 1: Element # 37 : {40,106,105,204,208,200},8
Rank 1: Element # 38 : {42,110,85,223,227,108},8

I hope you wil be able to work with my example to reproduce and solve 
this problem!

Compile & run with:

  mpic++ -o bugmaster mpich_bug_indexed_type.cc
  mpirun -n 2 bugmaster

Here's  Eric's the test case:

[mpich_bug_indexed_type.cc.txt](https://github.com/pmodels/mpich/files/3277846/mpich_bug_indexed_type.cc.txt)

**Comment by raffenet** [comment] 2019-06-11 18:01
Duplicate of #3830.

**Closed by raffenet** 2019-06-11 18:01 UTC
