### ISSUE TITLE
autogen.sh -- "warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body"

### ISSUE THREAD

**Issue by mblockso** [pmodels/mpich#2408] opened 2016-11-04 13:26 UTC
When I run autogen.sh on bgq I get this warning multiple times....

```
configure.ac:92: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2661: _AC_LINK_IFELSE is expanded from...
../../lib/autoconf/general.m4:2678: AC_LINK_IFELSE is expanded from...
config/libtool.m4:4161: _LT_LINKER_SHLIBS is expanded from...
config/libtool.m4:5236: _LT_LANG_C_CONFIG is expanded from...
config/libtool.m4:138: _LT_SETUP is expanded from...
config/libtool.m4:67: LT_INIT is expanded from...
configure.ac:92: the top level
```

**Comment by raffenet** [comment] 2016-11-21 17:21
@mblockso is this from a build with embedded OFI? Based on the line number, I suspect it is not coming from MPICH but from libfabric's `autogen.sh`.

**Comment by mblockso** [comment] 2016-11-21 19:00
Yes .. most likely it is from an embedded ofi build. I'll look more closely at the warnings when Vesta gets out of maintenance and let you know what I find.

**Comment by raffenet** [comment] 2016-11-29 22:25
@mblockso were you able to confirm this was coming from libfabric?

**Comment by mblockso** [comment] 2016-11-29 22:56
sorry .. haven't had time to look at this yet.

**Comment by raffenet** [comment] 2018-08-15 14:53
Almost positive this wasn't from an MPICH configure file. Closing after unable to reproduce.

**Closed by raffenet** 2018-08-15 14:53 UTC
