### ISSUE TITLE
misc: warnings on MPI_STATUS_IGNORE etc with  gcc-11.2.1

### ISSUE THREAD

**Issue by balay** [pmodels/mpich#5687] opened 2021-11-19 17:26 UTC
I'm not sure if this is a compiler issue - or code isse [occurs with mpich - but not openmpi]

This is a 32bit build with `gcc (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1)` on Fedora 35

```
[glci@pj03 petsc]$ make V=1 PETSC_ARCH=arch-ci-linux-gcc-complex-opt-32bit arch-ci-linux-gcc-complex-opt-32bit/obj/sys/utils/mpits.o
/home/glci/petsc-hash-pkgs/494b06380/bin/mpicc -c -m32 -fPIC -Wall -Wwrite-strings -Wno-strict-aliasing -Wno-unknown-pragmas -g -O    -I/home/glci/petsc/include -I/home/glci/petsc/arch-ci-linux-gcc-complex-opt-32bit/include -I/home/glci/petsc-hash-pkgs/494b06380/include    -MMD -MP /home/glci/petsc/src/sys/utils/mpits.c -o arch-ci-linux-gcc-complex-opt-32bit/obj/sys/utils/mpits.o
/home/glci/petsc/src/sys/utils/mpits.c: In function ‘PetscCommBuildTwoSidedFReq_Ibarrier’:
/home/glci/petsc/src/sys/utils/mpits.c:425:14: warning: ‘MPI_Testall’ accessing 20 bytes in a region of size 0 [-Wstringop-overflow=]
  425 |       ierr = MPI_Testall(nsends,sendreqs,&sent,MPI_STATUSES_IGNORE);CHKERRMPI(ierr);
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/glci/petsc/src/sys/utils/mpits.c:425:14: note: referencing argument 4 of type ‘MPI_Status *’
In file included from /home/glci/petsc/include/petscsys.h:162,
                 from /home/glci/petsc/src/sys/utils/mpits.c:1:
/home/glci/petsc-hash-pkgs/494b06380/include/mpi.h:947:5: note: in a call to function ‘MPI_Testall’
  947 | int MPI_Testall(int count, MPI_Request array_of_requests[], int *flag,
      |     ^~~~~~~~~~~
/home/glci/petsc/src/sys/utils/mpits.c: In function ‘PetscCommBuildTwoSided_Ibarrier’:
/home/glci/petsc/src/sys/utils/mpits.c:125:14: warning: ‘MPI_Testall’ accessing 20 bytes in a region of size 0 [-Wstringop-overflow=]
  125 |       ierr = MPI_Testall(nsends,sendreqs,&sent,MPI_STATUSES_IGNORE);CHKERRMPI(ierr);
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/glci/petsc/src/sys/utils/mpits.c:125:14: note: referencing argument 4 of type ‘MPI_Status *’
In file included from /home/glci/petsc/include/petscsys.h:162,
                 from /home/glci/petsc/src/sys/utils/mpits.c:1:
/home/glci/petsc-hash-pkgs/494b06380/include/mpi.h:947:5: note: in a call to function ‘MPI_Testall’
  947 | int MPI_Testall(int count, MPI_Request array_of_requests[], int *flag,
      |     ^~~~~~~~~~~
In file included from /home/glci/petsc/include/petscsys.h:1674,
                 from /home/glci/petsc/src/sys/utils/mpits.c:1:
/home/glci/petsc/src/sys/utils/mpits.c: In function ‘PetscCommBuildTwoSidedF’:
/home/glci/petsc/include/petsclog.h:551:81: warning: ‘MPI_Waitall’ accessing 20 bytes in a region of size 0 [-Wstringop-overflow=]
  551 |   ((petsc_wait_all_ct++,petsc_sum_of_waits_ct += (PetscLogDouble) (count),0) || MPI_Waitall((count),(array_of_requests),(array_of_statuses)))
      |                                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/glci/petsc/src/sys/utils/mpits.c:494:10: note: in expansion of macro ‘MPI_Waitall’
  494 |   ierr = MPI_Waitall(nto*ntags,toreqs,MPI_STATUSES_IGNORE);CHKERRMPI(ierr);
      |          ^~~~~~~~~~~
/home/glci/petsc/include/petsclog.h:551:81: note: referencing argument 3 of type ‘MPI_Status *’
  551 |   ((petsc_wait_all_ct++,petsc_sum_of_waits_ct += (PetscLogDouble) (count),0) || MPI_Waitall((count),(array_of_requests),(array_of_statuses)))
      |                                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/glci/petsc/src/sys/utils/mpits.c:494:10: note: in expansion of macro ‘MPI_Waitall’
  494 |   ierr = MPI_Waitall(nto*ntags,toreqs,MPI_STATUSES_IGNORE);CHKERRMPI(ierr);
      |          ^~~~~~~~~~~
In file included from /home/glci/petsc/include/petscsys.h:162,
                 from /home/glci/petsc/src/sys/utils/mpits.c:1:
/home/glci/petsc-hash-pkgs/494b06380/include/mpi.h:946:5: note: in a call to function ‘MPI_Waitall’
  946 | int MPI_Waitall(int count, MPI_Request array_of_requests[], MPI_Status array_of_statuses[]) MPICH_API_PUBLIC;
      |     ^~~~~~~~~~~
In file included from /home/glci/petsc/include/petscsys.h:1674,
                 from /home/glci/petsc/src/sys/utils/mpits.c:1:
/home/glci/petsc/include/petsclog.h:551:81: warning: ‘MPI_Waitall’ accessing 20 bytes in a region of size 0 [-Wstringop-overflow=]
  551 |   ((petsc_wait_all_ct++,petsc_sum_of_waits_ct += (PetscLogDouble) (count),0) || MPI_Waitall((count),(array_of_requests),(array_of_statuses)))
      |                                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/glci/petsc/src/sys/utils/mpits.c:495:10: note: in expansion of macro ‘MPI_Waitall’
  495 |   ierr = MPI_Waitall(*nfrom*ntags,fromreqs,MPI_STATUSES_IGNORE);CHKERRMPI(ierr);
      |          ^~~~~~~~~~~
/home/glci/petsc/include/petsclog.h:551:81: note: referencing argument 3 of type ‘MPI_Status *’
  551 |   ((petsc_wait_all_ct++,petsc_sum_of_waits_ct += (PetscLogDouble) (count),0) || MPI_Waitall((count),(array_of_requests),(array_of_statuses)))
      |                                                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/glci/petsc/src/sys/utils/mpits.c:495:10: note: in expansion of macro ‘MPI_Waitall’
  495 |   ierr = MPI_Waitall(*nfrom*ntags,fromreqs,MPI_STATUSES_IGNORE);CHKERRMPI(ierr);
      |          ^~~~~~~~~~~
In file included from /home/glci/petsc/include/petscsys.h:162,
                 from /home/glci/petsc/src/sys/utils/mpits.c:1:
/home/glci/petsc-hash-pkgs/494b06380/include/mpi.h:946:5: note: in a call to function ‘MPI_Waitall’
  946 | int MPI_Waitall(int count, MPI_Request array_of_requests[], MPI_Status array_of_statuses[]) MPICH_API_PUBLIC;
      |     ^~~~~~~~~~~
```

I see mpi.h has:
```
#define MPI_STATUSES_IGNORE (MPI_Status *)1
```
Changing this '0' gets rid of the warning (openmpi uses this) [same issue with 'MPI_STATUS_IGNORE']
```
#define MPI_STATUSES_IGNORE (MPI_Status *)0
```

```
[glci@pj03 petsc]$ make V=1 PETSC_ARCH=arch-ci-linux-gcc-complex-opt-32bit arch-ci-linux-gcc-complex-opt-32bit/obj/sys/utils/mpits.o
/home/glci/petsc-hash-pkgs/494b06380/bin/mpicc -c -m32 -fPIC -Wall -Wwrite-strings -Wno-strict-aliasing -Wno-unknown-pragmas -g -O    -I/home/glci/petsc/include -I/home/glci/petsc/arch-ci-linux-gcc-complex-opt-32bit/include -I/home/glci/petsc-hash-pkgs/494b06380/include    -MMD -MP /home/glci/petsc/src/sys/utils/mpits.c -o arch-ci-linux-gcc-complex-opt-32bit/obj/sys/utils/mpits.o
[glci@pj03 petsc]$ /home/glci/petsc-hash-pkgs/494b06380/bin/mpichversion 
MPICH Version:          3.4.2
MPICH Release date:     Wed May 26 15:51:40 CDT 2021
MPICH Device:           ch3:nemesis
MPICH configure:        --prefix=/home/glci/petsc-hash-pkgs/494b06380 MAKE=/usr/bin/gmake --libdir=/home/glci/petsc-hash-pkgs/494b06380/lib CC=gcc CFLAGS=-m32 -fPIC -g -O AR=/usr/bin/ar ARFLAGS=cr CXX=g++ CXXFLAGS=-m32 -fPIC -g -O -fPIC -std=gnu++17 FFLAGS=-m32 -fPIC -ffree-line-length-0 -g -O -fallow-argument-mismatch FC=gfortran F77=gfortran FCFLAGS=-m32 -fPIC -ffree-line-length-0 -g -O -fallow-argument-mismatch --enable-shared --with-pm=hydra --disable-java --with-device=ch3:nemesis --enable-g=meminit
MPICH CC:       gcc -m32 -fPIC -g -O   -O2
MPICH CXX:      g++ -m32 -fPIC -g -O -fPIC -std=gnu++17  -O2
MPICH F77:      gfortran -m32 -fPIC -ffree-line-length-0 -g -O -fallow-argument-mismatch  -O2
MPICH FC:       gfortran -m32 -fPIC -ffree-line-length-0 -g -O -fallow-argument-mismatch  -O2
MPICH Custom Information: 
[glci@pj03 petsc]$ 
```

**Comment by balay** [comment] 2021-11-20 16:23
Ah - I see this with regular 64bit builds aswell..

**Comment by hzhou** [comment] 2021-11-22 16:59
While many compiler warnings are helpful, I hate to be forced to add the complexity of workarounds just to appease the dumb part of the compiler. :disappointed: 

I see a few solutions:
1. Silence the warning with `-Wno-stringop-overflow`. Not really a solution.
2. Define the constants to `0`. It's only a fix because compiler made this an exception. It cornered us to not able to add additional constants.
3. Add dummy STATUS objects and points to it. We already do this with `MPI_UNWEIGHTED` and `MPI_WEIGHTS_EMPTY`. It is the most semantic correct solution, but the dummy objects add unnecessary (someone refers to it as accidental) complexity.

**Comment by balay** [comment] 2021-11-22 17:02
Right now - I'm using `-Wno-stringop-overflow` [as I'd like to use '-Werror' to catch issues in CI]

**Comment by hzhou** [comment] 2021-11-22 17:05
@raffenet What do you think regarding https://github.com/pmodels/mpich/issues/5687#issuecomment-975729787?

**Comment by raffenet** [comment] 2021-11-22 18:15
> @raffenet What do you think regarding [#5687 (comment)](https://github.com/pmodels/mpich/issues/5687#issuecomment-975729787)?

Unfortunately we're hamstrung by ABI with these values for now. We should definitely add them to the ABI wishlist.

If we do decide to change ABI, I think using `0` or `NULL` (solution 2) is OK. I guess an advantage to using a dummy struct (solution 3) is that we could throw and error on `NULL` usage, since that is not allowed by the specification.

**Comment by raffenet** [comment] 2021-11-22 18:21
Added a bullet onto the ABI wiki: https://github.com/pmodels/mpich/wiki/ABI-Change-Wishlist

**Comment by hzhou** [comment] 2021-11-22 18:37
> Added a bullet onto the ABI wiki: https://github.com/pmodels/mpich/wiki/ABI-Change-Wishlist

Good point that this is an ABI change, and at least for now, keeping it backward compatible is probably more significant than fixing a warning. That leaves option 1. I guess we can add `-Wno-stringop-overflow` to `configure` and add a note in README to advise application to do the same if they desire to use `-Werror`.

In fact, the more I look at this, the more I convinced this is a `gcc` regression.

**Comment by hzhou** [comment] 2021-11-29 16:52
@raffenet I am tempted to label this issue as `won't fix`. It is just warning annoyances. I am also convinced this is really a compiler regression issue. Your opinion?

**Comment by raffenet** [comment] 2021-11-29 17:29
I agree. My only question is do we submit feedback to the GCC folks?

**Comment by hzhou** [comment] 2021-11-29 17:33
> I agree. My only question is do we submit feedback to the GCC folks?

It will be nice to do that. @travisk1154 Are you interested in submitting the ticket to GCC?

**Comment by travisk1154** [comment] 2021-11-30 21:24
Sure thing!

**Comment by hzhou** [comment] 2022-01-06 23:01
Apparently `gcc` now is making a difference between 
```
int MPI_Waitall(int count, MPI_Request array_of_requests[], MPI_Status array_of_statuses[]);
```
and
```
int MPI_Waitall(int count, MPI_Request array_of_requests[], MPI_Status *array_of_statuses);
```

**Comment by hzhou** [comment] 2022-01-07 15:36
@balay Could you verify the patch in #5749 resolves the issue?

**Comment by balay** [comment] 2022-01-07 17:17
@hzhou Thanks! I've tried manual edit to mpi.h [with this change] - and that works!

**Closed** 2022-01-07 17:58 UTC
