### ISSUE TITLE
bug: MPI_Wait hangs on Blues with derived types for MPI_Irecv

### ISSUE THREAD

**Issue by dqwu** [pmodels/mpich#2645] opened 2017-06-06 16:18 UTC
Test code: https://gist.githubusercontent.com/dqwu/f7995abfae71c6920e52a1fd756d3108/raw/821389c54c139fe1a11b1232dead5c07b699d4e7/test_mpi_wait_derived_type_32p_4io.c
Note: the first 900+ lines are mostly hard-coded offsets and lengths, and the main() function is short.

The conditions are related to:
1) The issue is only reproducible on Blues so far (32 MPI tasks, 2 compute nodes).
2) The two aggregators (IO rank 0 and 2 in the test) run on different compute nodes of Blues.
3) MPI_Irecv uses some derived MPI types (created with MPI_Type_hindexed from MPI_BYTE). The issue is not reproducible if MPI_BYTE is directly used by MPI_Irecv.
4) OpenMPI on Blues works fine for this test.

The original test with this hanging behavior uses pnetcdf to write decomposed data to a file. The simplified test no longer depends on pnetcdf and MPI-IO. It mimics ADIOI_W_Exchange_data() in src/mpi/romio/adio/common/ad_write_coll.c, with the same data decomposition (in a different form) from original test, but no actual IO operations are performed.

In ADIOI_W_Exchange_data(), MPI_Isend uses MPI_BYTE but MPI_Irecv uses some derived types with matched size. This test program shows that this pattern might cause MPI_Wait to hang on MPI_Irecv in some cases.

**Comment by dqwu** [comment] 2017-06-19 21:13
A simplified test to reproduce the hanging issue on Blues: https://gist.githubusercontent.com/dqwu/02d75cfd202e5463723e222597e3370b/raw/15c7b6fe179d9e17d3aecb5b6b0dcc33a1e2825e/test_mpi_wait_derived_type_32p_4io_simplified.c

Original test code:
IO task 0 (world rank 0): 4 receive requests and 2 send requests
IO task 1 (world rank 8): 0 receive requests and 2 send requests
IO task 2 (world rank 16): 4 receive requests and 2 send requests
IO task 3 (world rank 24): 0 receive requests and 2 send requests

Simplified test code:
IO task 0 (world rank 0): 3 receive requests and 0 send request
IO task 1 (world rank 8): 0 receive request and 1 send request
IO task 2 (world rank 16): 0 receive request and 1 send request
IO task 3 (world rank 24): 0 receive request and 1 send request

**Comment by sudheer9** [comment] 2018-09-07 01:16
@dqwu I've not been able to reproduce the said behavior (hanging of MPI_Wait) running on Blues. I did follow the 3 conditions that were mentioned above. I've tried with the latest as well as the 3.2.x branches of MPICH.

**Comment by iulian787** [comment] 2018-09-07 18:15
I tried with this soft key
soft add +mpich-3.2-gcc-5.3.0 
script and results are here, on blues:
```
/home/iulian/tmp
-rw-r--r-- 1 iulian collab 2.1K Sep  7 12:52 scr.pbs.o2356783
-rw-r--r-- 1 iulian collab   51 Sep  7 12:52 scr.pbs.e2356783
-rw-r--r-- 1 iulian collab 2.2K Sep  7 12:52 scr.pbs.o2356784
-rw-r--r-- 1 iulian collab   51 Sep  7 12:52 scr.pbs.e2356784
-rw-r--r-- 1 iulian collab  196 Sep  7 12:50 scr.pbs
-rwxr-xr-x 1 iulian collab  97K Sep  7 12:31 a.out*
-rw-r--r-- 1 iulian collab 106K Sep  7 12:25 test_blues.c
```

it hangs out, as reported by Danqing, job was killed after one minute

**Comment by sudheer9** [comment] 2021-03-18 21:03
@dqwu @iulian787 if this is should still be an open issue. I could not reproduce this reported behavior with the lastet MPICH `master` on LCRC `Blues` system. I have tested with the latest available `gcc` `gcc/10.2.0` as well as with `gcc/5.3.0` on `Blues`.

**Comment by dqwu** [comment] 2021-03-18 21:43
> @dqwu @iulian787 if this is should still be an open issue. I could not reproduce this reported behavior with the lastet MPICH `master` on LCRC `Blues` system. I have tested with the latest available `gcc` `gcc/10.2.0` as well as with `gcc/5.3.0` on `Blues`.

@sudhee9
See if you can still reproduce this issue with old mpich-3.2-gcc-5.3.0 module. However, if the latest MPICH module on Blues cannot reproduce it, we can consider closing this issue.

**Comment by hzhou** [comment] 2021-03-18 21:46
@sudheer9 It is always good to test a few major release points to get an idea at which point we have fixed the issue.

**Comment by sudheer9** [comment] 2021-03-18 21:56
@hzhou sure, will test as suggested.

**Comment by sudheer9** [comment] 2021-03-23 21:43
I could not load the old  mpich-3.2-gcc-5.3.0  module on Blues. Given we cannot reproduce this reported error on latest `master` and this issue seem system or configuration specific, I propose to close this issue for now.

**Closed** 2021-03-23 22:05 UTC
Labels: need confirm
