### ISSUE TITLE
Replace the obsolete `gethostbyname` with `getaddrinfo`

### ISSUE THREAD

**Issue by yfguo** [pmodels/mpich#2889] opened 2017-12-06 18:06 UTC
`gethostbyname` is obsolete and does not support IPv6. It should be replaced by `getaddrinfo` per POSIX.1-2008 
- [ ] create MPL version
- [ ] fix checking in configure
- [ ] replace obsolete version

**Comment by pavanbalaji** [comment] 2017-12-06 19:12
This should be done in `MPL` and used in both `mpich` and `hydra` consistently.

**Comment by szhao8** [comment] 2017-12-08 20:58
Hi, Yanfei & Pavan, 
Thank you for your comment. Just friendly reminder: 
If you have the other functions listed below which only support ipv4, please also replace them together to make sure MPICH can work properly under IPV6 environment.
IPV4                                                                          IPV6
gethostbyname/getservbyname                              getaddrinfo
gethostbyaddr                                                          getnameinfo
inet_ntoa                                                                   inet_ntop
inet_aton                                                                   inet_pton
socket/bind/accept/recv/recvfrom/send/sendto      function name same, argument list change. 

Thanks,

**Comment by szhao8** [comment] 2018-01-29 21:56
If everyone is busy with other issues, may I finish this ticket by myself and then submit a pull request?

**Comment by pavanbalaji** [comment] 2018-01-29 21:57
@szhao8 We always welcome and appreciate pull requests.  Thanks!

**Comment by szhao8** [comment] 2018-02-28 00:07
@yfguo @pavanbalaji Hi Yanfei & Pavan
Since I'm pretty new to this project, I didn't know the whole flow too much. Could you explain the steps above? 
Currently i just directly search and replace all related ipv4 functions networking functions with ipv6 functions so that they can work under ipv4/ipv6? I also run some regression testing, didn't incur more errors. Isn't these enough?

**Comment by pavanbalaji** [comment] 2018-02-28 03:42
@szhao8 you can submit a pull request with your changes.  Then someone can review it for you and run it through our regression testing as well.  They might ask for changes to the PR based on the review as well.

You might want to read the `CONTRIBUTING` document in `mpich/master` for tips on how to write the code so it'd be accepted in mpich: https://github.com/pmodels/mpich/blob/master/CONTRIBUTING

**Comment by szhao8** [comment] 2018-02-28 04:01
@pavanbalaji Thanks, Let me read this first, I will submit a PR according to the rule later.

**Comment by szhao8** [comment] 2018-03-13 04:42
@yfguo @pavanbalaji Hi, I have submitted a pull request, please help review it and I can accomodate more changes to make it successfully merged finally.

**Closed** 2019-10-17 17:21 UTC
Labels: enhancement
