### ISSUE TITLE
Hydra/mpiexec fails on port scan

### ISSUE THREAD

**Issue by arewedancer** [pmodels/mpich#3520] opened 2019-01-18 18:16 UTC
Hi,
   Hydra/mpiexec exits on assert fail when port scanning mpiexec listening port (TCP)
Errors:
```
[mpiexec@] HYD_pmcd_pmiserv_proxy_init_cb (pm/pmiserv/pmiserv_cb.c:450): assert (!closed) failed
[mpiexec@] HYDT_dmxu_poll_wait_for_event (tools/demux/demux_poll.c:77): callback returned error status
[mpiexec@] HYD_pmci_wait_for_completion (pm/pmiserv/pmiserv_pmci.c:196): error waiting for event
[mpiexec@] main (ui/mpich/mpiexec.c:336): process manager error waiting for completion
```

Steps to reproduce this crash:
grep listening port of mpiexec ->
nmap or nc port scan:
nmap -sT -p <port> IP
nc -z -v -w1 host_IP port

**Comment by pavanbalaji** [comment] 2019-01-18 19:44
Duplicate of #2106.

**Closed by pavanbalaji** 2019-01-18 19:44 UTC
Labels: duplicate

**Comment by arewedancer** [comment] 2019-01-22 15:00
Not sure it's the same issue but this one breaks at mpiexec:
https://github.com/pmodels/mpich/blob/06efcc05762712ddf7ba5f37869c7d10c29ad14a/src/pm/hydra/pm/pmiserv/pmiserv_cb.c#L446
Rank/process in my test program doesn't involve any mpi_recv/send. They simply wake up every few seconds and print a message.
