### ISSUE TITLE
build: --disable-error-checking  build broken

### ISSUE THREAD

**Issue by mchaarawi** [pmodels/mpich#4990] opened 2021-01-11 23:11 UTC
when configuring with --disable-error-checking, i get a compile error:

```
src/mpi/topo/cart_coords.c: In function ‘PMPI_Cart_coords’:
src/mpi/topo/cart_coords.c:118:9: error: label ‘fn_fail’ used but not defined
         goto fn_fail;
         ^~~~
make[2]: *** [Makefile:30275: src/mpi/topo/lib_libmpi_la-cart_coords.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
src/mpi/topo/cart_get.c: In function ‘PMPI_Cart_get’:
src/mpi/topo/cart_get.c:123:9: error: label ‘fn_fail’ used but not defined
         goto fn_fail;
         ^~~~
make[2]: *** [Makefile:30289: src/mpi/topo/lib_libmpi_la-cart_get.lo] Error
```

**Comment by raffenet** [comment] 2021-03-01 19:18
@sudheer9 should be somewhat straight-forward to investigate/fix this build issue.

**Comment by hzhou** [comment] 2021-03-01 19:49
@sudheer9 Both files are now auto-generated. Make sure to check whether the error still exists in the `main` branch first.

**Comment by sudheer9** [comment] 2021-03-08 22:39
@mchaarawi @hzhou I tested configuring with --disable-error-checking in `main` branch and do not see the above error. The build passes successfully.

**Comment by hzhou** [comment] 2021-03-08 22:44
@sudheer9 Could you check 3.4.1 release? -- Just for understanding.

**Comment by sudheer9** [comment] 2021-03-09 05:33
@hzhou checked with the 3.4.1 release and do not see the issue, could not reproduce the build error noted above.

**Comment by mchaarawi** [comment] 2021-03-09 17:32
i just tried with latest main, and it worked for me. so it seems this issue was fixed at some point.

**Comment by sudheer9** [comment] 2021-03-09 18:12
Thanks @mchaarawi, closing the issue.

**Closed** 2021-03-09 18:12 UTC
