### ISSUE TITLE
ch4/ofi: rget_testall returns incorrect value

### ISSUE THREAD

**Issue by hajimefu** [pmodels/mpich#4011] opened 2019-09-03 21:43 UTC
This is likely to be an intermittent failure.
```
not ok 957 - ./rma/rget_testall 2
  ---
  Directory: ./rma
  File: rget_testall
  Num-procs: 2
  Timeout: 180
  Date: "Tue Aug 20 16:39:12 2019"
  ...
## Test output (expected 'No Errors'):
## 1 - Got val1 = 0, val2 = 0, expected 1, 2
##  Found 1 errors
```

**Comment by hzhou** [comment] 2019-09-03 22:22
@hajimefu Could you add the configuration -- is it `ofi-external`? Also, if you (or anyone) encounter it more than once, it is nice to add comments here on "how intermittent" it is.

**Comment by hajimefu** [comment] 2019-09-04 18:01
In our environment we use embedded OFI, so external OFI is not a key. For frequency, I can just say it's quite rare. I quickly tested for about 500 times locally but haven't seen one failure.

Due to this rare nature of the failure I don't have more precise configuration information at the moment. I'll update here once I get more info on this.

**Comment by raffenet** [comment] 2019-09-06 21:10
This happens somewhat consistently when testing on Solaris nodes in Jenkins. https://pmrs-jenkins.cels.anl.gov/job/mpich-master-ch3-solaris/18/compiler=gnu,jenkins_configure=debug,label=pmrs-sol64-240-01/testReport/junit/(root)/summary_junit_xml/864_____rma_rget_testall_2__/

**Comment by hzhou** [comment] 2019-09-15 03:32
On `ch3-tcp-solaris`, the error seems slightly different:
```
not ok 1063 - ./rma/rget_testall 2
  ---
  Directory: ./rma
  File: rget_testall
  Num-procs: 2
  Timeout: 180
  Date: "Sat Sep 14 00:19:07 2019"
  ...
## Test output (expected 'No Errors'):
## 1 - Got val1 = 5719568, val2 = 0, expected 1, 2
##  Found 1 errors
```

**Comment by raffenet** [comment] 2019-09-16 01:26
Each of these happened when I did some testing on my laptop. I found it can be reproduced in about 1:10000 runs.

**Comment by hzhou** [comment] 2019-09-16 03:40
>  I found it can be reproduced in about 1:10000 runs.

Good lord!

**Comment by hajimefu** [comment] 2019-09-19 14:28
Interesting. So this is happening with CH3 too? If that's the case it's suggesting that the issue is likely to be in upper (MPI) layer, not device or under.

**Comment by hajimefu** [comment] 2019-09-19 19:37
Just FYI, in our systems, it seems that the failure probability goes up when running on multi-node.  It's not always but maybe 1 failure in 10-20 trials or so.

**Comment by rzambre** [comment] 2019-09-19 19:45
Any experience of this error popping up with `ch4:ucx`?

**Comment by hzhou** [comment] 2019-09-19 20:19
So far seems `ofi` specific.

**Comment by raffenet** [comment] 2019-10-02 14:24
Duplicate of #3558.

**Closed by raffenet** 2019-10-02 14:24 UTC
