### ISSUE TITLE
Segfault in MPI_Reduce

### ISSUE THREAD

**Issue by eschnett** [pmodels/mpich#5700] opened 2021-11-26 23:53 UTC
I encounter a weird segfault in `MPI_Reduce`. This is reproducible with a simple code:

```C
#include <mpi.h>
#include <stdio.h>
#include <stdlib.h>
int main(int argc, char **argv) {
  MPI_Init(&argc, &argv);
  MPI_Comm comm = MPI_COMM_WORLD;
  int size;
  MPI_Comm_size(comm, &size);
  int rank;
  MPI_Comm_rank(comm, &rank);
  int root = size - 1;
  int send = rank;
  int recv;
  for (int i = 0; i < 10; ++i) {
    if (rank == 0)
      fprintf(stderr, "MPI_Reduce i=%d\n", i);
    MPI_Reduce(&send, rank == root ? &recv : NULL, 1, MPI_INT, MPI_SUM, root,
               comm);
  }
  MPI_Finalize();
  return 0;
}
```

I believe this code is correct. The two noteworthy items are (1) the root is not process 0, and (2) the receive buffer pointer is null on non-root processes.

When I build this on macOS with MPICH 3.4.2 installed via Homebrew or via MacPorts, and then run with more than 1 process, the code segfaults in `MPI_Reduce` during the 5th (sic!) iteration. This is repeatable. The same segfault also occurs when calling MPICH from [Julia](https://julialang.org); see e.g. [here](https://github.com/JuliaParallel/MPI.jl/runs/4217897754), where the relevant output lines are
```
signal (11): Segmentation fault: 11
in expression starting at /Users/runner/work/MPI.jl/MPI.jl/test/test_reduce.jl:30
_platform_memmove$VARIANT$Nehalem at /usr/lib/system/libsystem_platform.dylib (unknown line)
```

The segfault does not occur on Linux. It also does not occur when I build MPICH 3.4.2 manually using the same (as far as I can tell) build options that the Homebrew recipe uses.

The segfault goes away (in Julia) when passing a valid array instead of `NULL` for the receive buffer. It also goes away when the root is process 0.

I checked the logic in `MPI_Reduce` in MPICH. The code for handling `root != 0` is certainly complex. However, the code clearly never accesses the receive buffer pointer on non-root processes.

I am puzzled by these symptoms. My best left-over conjectures are
- MPICH does not quite follow the C standard, and the compiler (GCC 11.2) mis-optimizes the code
- GCC itself has a bug that somehow manifests itself only on macOS.

**Comment by hzhou** [comment] 2021-11-27 04:18
@eschnett Is it possible to get a backtrace?

**Comment by eschnett** [comment] 2021-11-27 17:36
It's difficult since `mpiexec` doesn't propagate `ulimit` settings, so I don't know how to get a core file. I have added a delay after startup and attached two debuggers to the running processes. Here are the respective stack traces (running with 2 processes):

The failing process (rank 0):
```
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x00007ff819bba266 libsystem_platform.dylib`_platform_memmove$VARIANT$Haswell + 198
    frame #1: 0x0000000101761c4b libpmpi.12.dylib`fastpath_memcpy + 683
    frame #2: 0x0000000101761cd2 libpmpi.12.dylib`MPIR_Typerep_unpack + 98
    frame #3: 0x000000010059d436 libmpi.12.dylib`MPIR_Localcopy + 614
    frame #4: 0x0000000101562792 libpmpi.12.dylib`MPIDI_POSIX_mpi_reduce_release_gather + 1570
    frame #5: 0x0000000101562050 libpmpi.12.dylib`MPIDI_SHM_mpi_reduce + 448
    frame #6: 0x00000001015603c6 libpmpi.12.dylib`MPIR_Reduce + 2022
    frame #7: 0x000000010055e1fb libmpi.12.dylib`MPI_Reduce + 4843
    frame #8: 0x0000000100271f04 test_reduce`main(argc=1, argv=0x00007ff7bfc91568) at test_reduce.c:19:5
    frame #9: 0x000000010dc414fe dyld`start + 462
```

The other process (rank 1):
```
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x000000010d36b270 libpmpi.12.dylib`sock_pe_progress_ep_tx
    frame #1: 0x000000010d35c569 libpmpi.12.dylib`sock_cq_progress + 89
    frame #2: 0x000000010d35d447 libpmpi.12.dylib`sock_cq_sreadfrom + 471
    frame #3: 0x000000010cc03a66 libpmpi.12.dylib`MPIDI_OFI_progress + 118
    frame #4: 0x000000010cbd6c5f libpmpi.12.dylib`progress_test + 175
    frame #5: 0x000000010cbd72dd libpmpi.12.dylib`MPID_Progress_wait + 77
    frame #6: 0x000000010ca66751 libpmpi.12.dylib`MPIR_Wait_state + 81
    frame #7: 0x000000010cb69536 libpmpi.12.dylib`MPIC_Wait + 118
    frame #8: 0x000000010cb69c7c libpmpi.12.dylib`MPIC_Recv + 556
    frame #9: 0x000000010c98ba24 libpmpi.12.dylib`MPIDI_POSIX_mpi_reduce_release_gather + 2228
    frame #10: 0x000000010c98b050 libpmpi.12.dylib`MPIDI_SHM_mpi_reduce + 448
    frame #11: 0x000000010c9893c6 libpmpi.12.dylib`MPIR_Reduce + 2022
    frame #12: 0x000000010b9871fb libmpi.12.dylib`MPI_Reduce + 4843
    frame #13: 0x000000010b69af04 test_reduce`main(argc=1, argv=0x00007ff7b4868568) at test_reduce.c:19:5
    frame #14: 0x000000011147a4fe dyld`start + 462
```

As I mentioned, I couldn't reproduce the problem when building MPICH myself. The system MPICH (here from MacPorts) does apparently not include debug information. I don't know how useful the backtrace is. It wasn't useful to me. I think the compiler inlined many functions, so the actual source code locations are basically impossible to determine.

**Comment by hzhou** [comment] 2021-11-27 17:47
@eschnett Thanks for the backtrace. I believe this bug was fixed in https://github.com/pmodels/mpich/pull/5409/commits/10cb9c99a9720795f5e6d5af5cfc15b3ac237bd2
The latest release 4.0b1 contains that fix. The stable release of 4.0 will come out in a few weeks.

**Comment by hzhou** [comment] 2022-01-06 17:06
@eschnett Can you check or confirm that the issue is fixed in the latest release?

**Comment by hzhou** [comment] 2022-02-02 04:06
Lack of response. Assume it is fixed. Close now.

**Closed by hzhou** 2022-02-02 04:06 UTC
