### ISSUE TITLE
mpich-3.3a3: duplicate symbol _MPIR_Type_get_contents on OSX

### ISSUE THREAD

**Issue by balay** [pmodels/mpich#2936] opened 2018-01-23 01:47 UTC
I get the following error with mpich-3.3a3 static build on OSX - but no such issue with mpich-3.3a2
[Also mpich-3.3a3 shared build does not give this error]

```
/Users/balay/petsc/arch-darwin-c-debug/bin/mpicc -o ex19.o -c -Wall -Wwrite-strings -Wno-strict-aliasing -Wno-unknown-pragmas -fstack-protector -Qunused-arguments -g3   -I/Users/balay/petsc/include -I/Users/balay/petsc/arch-darwin-c-debug/include    `pwd`/ex19.c
/Users/balay/petsc/arch-darwin-c-debug/bin/mpicc -Wl,-multiply_defined,suppress -Wl,-multiply_defined -Wl,suppress -Wl,-commons,use_dylibs -Wl,-search_paths_first -Wl,-no_compact_unwind -Wl,-multiply_defined,suppress -Wl,-multiply_defined -Wl,suppress -Wl,-commons,use_dylibs -Wl,-search_paths_first -Wl,-no_compact_unwind   -Wall -Wwrite-strings -Wno-strict-aliasing -Wno-unknown-pragmas -fstack-protector -Qunused-arguments -g3  -o ex19  ex19.o -L/Users/balay/petsc/arch-darwin-c-debug/lib -L/usr/local/lib -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/lib/darwin -L/usr/local/Cellar/gcc/7.2.0/lib/gcc/7/gcc/x86_64-apple-darwin17.0.0/7.2.0 -L/usr/local/Cellar/gcc/7.2.0/lib/gcc/7 -Wl,-rpath,/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/lib/darwin -lpetsc -llapack -lblas -lclang_rt.osx -lmpifort -lgfortran -lgcc_ext.10.5 -lquadmath -lclang_rt.osx -lmpicxx -lc++ -lclang_rt.osx -ldl -lmpi -lpmpi -lm -lpthread -lSystem -lclang_rt.osx -ldl
duplicate symbol _MPIR_Type_get_contents in:
    /Users/balay/petsc/arch-darwin-c-debug/lib/libmpi.a(lib_libmpi_la-type_get_contents.o)
    /Users/balay/petsc/arch-darwin-c-debug/lib/libpmpi.a(lib_libpmpi_la-type_get_contents.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Attaching corresponding config.log
[config.log](https://github.com/pmodels/mpich/files/1654193/config.log)

**Comment by raffenet** [comment] 2018-01-25 22:04
@balay could you send your example code `ex19.c`? I want to make sure I can reproduce this correctly.

**Comment by balay** [comment] 2018-01-25 22:43
Its a petsc example - so the MPI calls are from the library. To
reproduce - you would have to build PETSc

curl -O http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-3.8.3.tar.gz
[extract and then run]
./configure CC=mpicc CXX=mpicxx FC=mpif90 --with-shared-libraries=0
make
make test

I haven't attempted to reproduce with non-petsc test code..

**Comment by balay** [comment] 2018-01-26 00:09
BTW: There are only a few MPIR_ symbols in libmpi.a - perhaps none of them should be in libmpi.a?

balay@ipro^~/petsc/arch-test/lib(next) $ nm -o libmpi.a |grep _MPIR_ |grep ' T '
libmpi.a:lib_libmpi_la-op_commutative.o: 0000000000000000 T _MPIR_Op_commutative
libmpi.a:lib_libmpi_la-type_dup.o: 0000000000000000 T _MPIR_Type_dup
libmpi.a:lib_libmpi_la-type_get_contents.o: 0000000000000000 T _MPIR_Type_get_contents
libmpi.a:lib_libmpi_la-type_create_resized.o: 0000000000000000 T _MPIR_Type_create_resized
libmpi.a:lib_libmpi_la-all_romio_symbols.o: 0000000000000000 T _MPIR_All_romio_symbols
libmpi.a:mpich_fileutil.o: 0000000000000070 T _MPIR_ROMIO_Get_file_errhand
libmpi.a:mpich_fileutil.o: 0000000000000000 T _MPIR_ROMIO_Set_file_errhand
libmpi.a:mpir-mpioinit.o: 0000000000000000 T _MPIR_MPIOInit
libmpi.a:mpir_cst_filesys.o: 0000000000000000 T _MPIR_Comm_split_filesystem
libmpi.a:status_setb.o: 0000000000000000 T _MPIR_Status_set_bytes


balay@ipro^~/petsc/arch-test/lib(next) $ nm -o libmpi.a |grep lib_libmpi_la-type_get_contents.o |grep ' T '
libmpi.a:lib_libmpi_la-type_get_contents.o: 0000000000000000 T _MPIR_Type_get_contents
libmpi.a:lib_libmpi_la-type_get_contents.o: 0000000000000510 T _MPI_Type_get_contents

balay@ipro^~/petsc/arch-test/lib(next) $ nm -o libmpi.a |grep lib_libmpi_la-iprobe.o |grep ' T '
libmpi.a:lib_libmpi_la-iprobe.o: 0000000000000000 T _MPI_Iprobe
balay@ipro^~/petsc/arch-test/lib(next) $ nm -o libmpi.a |grep lib_libmpi_la-bcast.o |grep ' T '
libmpi.a:lib_libmpi_la-bcast.o: 0000000000000000 T _MPI_Bcast
balay@ipro^~/petsc/arch-test/lib(next) $

**Comment by balay** [comment] 2018-01-26 00:46
Ok - here is a cooked-up [non-petsc] test code to get this error

balay@ipro^~/junk $ cat x.c
extern void MPI_Type_get_contents(void);
extern void ADIOI_Optimize_flattened(void);

int main(void)
{
  MPI_Type_get_contents();
  ADIOI_Optimize_flattened();
  return 0;
}
balay@ipro^~/junk $ /Users/balay/petsc/arch-test/bin/mpicc x.c
duplicate symbol _MPIR_Type_get_contents in:
    /Users/balay/petsc/arch-test/lib/libmpi.a(lib_libmpi_la-type_get_contents.o)
    /Users/balay/petsc/arch-test/lib/libpmpi.a(lib_libpmpi_la-type_get_contents.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by raffenet** [comment] 2018-01-29 15:11
@balay thanks, that reproducer helped. I think I've got this one addressed, as well.

**Comment by balay** [comment] 2018-01-29 15:59
Great!

Is there a plan for 3.3a4 soon?

If not - is there a nightly tarball that I can grab and test - and
perhaps use [for PETSc defaults]?

**Comment by raffenet** [comment] 2018-01-29 16:05
We plan to have a 3.3b1 out any day now. There is one outstanding feature that is close to being merged. I'll make sure to get these 2 build fixes included, as well.

Looks like our nightly tarball script stopped working again :frowning_face:. I'll make sure that gets fixed, too.

**Closed** 2018-01-30 14:54 UTC

**Comment by raffenet** [comment] 2018-01-30 15:01
@balay nightlies should be added to http://www.mpich.org/static/downloads/nightly/master/mpich/ once again. Now I'll get an email if the script breaks, too :smile:. Thanks for the report!
